services:
#    medicine.example:
#        class: Appstore\Bundle\MedicineBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    appstore.election.member.event.listener:
        class: Appstore\Bundle\ElectionBundle\EventListener\MemberListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.election.particular.event.listener:
        class: Appstore\Bundle\ElectionBundle\EventListener\ParticularListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore_election_member_import:
        class: Appstore\Bundle\ElectionBundle\Importer\Member
        calls:
              - [ setContainer, [ @service_container ] ]

    appstore_election.importer.member_import:
        class: Appstore\Bundle\ElectionBundle\Importer\MemberDataReader
        arguments: [ @phpexcel ]

    appstore_election_voter_import:
        class: Appstore\Bundle\ElectionBundle\Importer\Voter
        calls:
              - [ setContainer, [ @service_container ] ]

    appstore_election.importer.voter_import:
        class: Appstore\Bundle\ElectionBundle\Importer\VoterDataReader
        arguments: [ @phpexcel ]

