<?php

namespace Appstore\Bundle\AssetsBundle\Repository;
use \Doctrine\ORM\EntityRepository;

/**
 * ParticularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticularRepository extends EntityRepository
{
	public function getLastId($inventory)
	{
		$qb = $this->createQueryBuilder('e');
		$qb->select('count(e.id)');
		$count = $qb->getQuery()->getSingleScalarResult();
		if($count > 0 ){
			return $count+1;
		}else{
			return 1;
		}

	}

	public function searchAutoComplete($q)
	{
		$query = $this->createQueryBuilder('e');
		$query->select('e.name as id');
		$query->addSelect('e.name as text');
		$query->where($query->expr()->like("e.name", "'$q%'"  ));
		$query->groupBy('e.id');
		$query->orderBy('e.name', 'ASC');
		$query->setMaxResults( '10' );
		return $query->getQuery()->getResult();

	}
}
