medicine:
    path:     /
    defaults: { _controller: "MedicineBundle:MedicineCompany:index" }

medicine_show:
    path:     /{id}/show
    defaults: { _controller: "MedicineBundle:MedicineCompany:show" }

medicine_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:MedicineCompany:new" }

medicine_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:MedicineCompany:create" }
    methods:  POST

medicine_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:MedicineCompany:edit" }

medicine_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:MedicineCompany:update" }
    methods:  [POST, PUT]

medicine_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:MedicineCompany:delete" }
    methods:  [POST, DELETE]

medicine_search:
    path:     /medicine-search
    defaults: { _controller: "MedicineBundle:MedicineBrand:autoSearchMedicine" }
    options:
            expose: true

generic_search:
    path:     /generic-search
    defaults: { _controller: "MedicineBundle:MedicineBrand:autoSearchGeneric" }
    options:
            expose: true

medicine_name:
    path:      /{medicine}/medicine-name
    defaults: { _controller: "MedicineBundle:MedicineBrand:searchProductName" }
    options:
            expose: true

medicine_user:
    path:     /medicine-user
    defaults: { _controller: "MedicineBundle:Medicine:index" }