medicine_instantpurchase:
    path:     /
    defaults: { _controller: "MedicineBundle:InstantPurchase:index" }

medicine_instantpurchase_show:
    path:     /{id}/show
    defaults: { _controller: "MedicineBundle:InstantPurchase:show" }

medicine_instantpurchase_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:InstantPurchase:new" }

medicine_instantpurchase_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:InstantPurchase:edit" }

medicine_instantpurchase_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:InstantPurchase:update" }
    methods:  [POST, PUT]

medicine_instantpurchase_status:
    path:     /{id}/status
    defaults: { _controller: "MedicineBundle:InstantPurchase:edit" }


medicine_instantpurchase_approve:
    path:     /{id}/approve
    defaults: { _controller: "MedicineBundle:InstantPurchase:approve" }

medicine_instantpurchase_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:InstantPurchase:delete" }

medicine_instantpurchase_particular_search:
    path:     /{id}/medicine-stock-search
    defaults: { _controller: "MedicineBundle:InstantPurchase:particularSearch" }
    options:
            expose: true


medicine_instantpurchase_particular_add:
    path:     /particular-add
    defaults: { _controller: "MedicineBundle:InstantPurchase:addParticular" }
    methods:  POST
    options:
            expose: true

medicine_instantpurchase_discount_update:
    path:     /instantpurchase/dicount-update
    defaults: { _controller: "MedicineBundle:InstantPurchase:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

medicine_instantpurchase_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "MedicineBundle:InstantPurchase:approved" }


medicine_instantpurchase_particular_delete:
    path:     /{invoice}/{id}/particular-delete
    defaults: { _controller: "MedicineBundle:InstantPurchase:invoiceParticularDelete" }

medicine_instantpurchase_print_invoice:
    path:     /{id}/print
    defaults: { _controller: "MedicineBundle:InstantPurchase:invoicePrint" }