medicine_report_purchase_summary:
    path:     /purchase-overview
    defaults: { _controller: "MedicineBundle:Report:purchaseOverview" }

medicine_report_purchase_vendor:
    path:     /purchase-vendor-outstanding
    defaults: { _controller: "MedicineBundle:Report:purchaseVendor" }

medicine_report_purchase_vendor_details:
    path:     /purchase-vendor-details
    defaults: { _controller: "MedicineBundle:Report:purchaseVendorDetails" }

medicine_report_purchase_vendor_sales:
    path:     /purchase-vendor-sales
    defaults: { _controller: "MedicineBundle:Report:purchaseVendorSales" }

medicine_report_purchase_brand_sales:
    path:     /purchase-brand-sales
    defaults: { _controller: "MedicineBundle:Report:purchaseBrandSales" }


medicine_report_purchase_vendor_stock:
    path:     /purchase-stock
    defaults: { _controller: "MedicineBundle:Report:purchaseStockItem" }

medicine_report_purchase_brand:
    path:     /purchase-brand-summary
    defaults: { _controller: "MedicineBundle:Report:purchaseBrand" }



medicine_report_purchase_details:
    path:     /purchase-vendor
    defaults: { _controller: "MedicineBundle:Report:purchaseVendor" }

medicine_report_purchase_stock:
    path:     /purchase-vendor-
    defaults: { _controller: "MedicineBundle:Report:purchaseVendor" }



medicine_report_purchase_brand_stock:
    path:     /purchase-stock
    defaults: { _controller: "MedicineBundle:Report:purchaseStockItem" }

medicine_report_sales_summary:
    path:     /sales-overview
    defaults: { _controller: "MedicineBundle:Report:salesOverview" }

medicine_report_sales_details:
    path:     /sales-details
    defaults: { _controller: "MedicineBundle:Report:salesDetails" }

medicine_report_sales_stock:
    path:     /sales-stock
    defaults: { _controller: "MedicineBundle:Report:salesStockItem" }

medicine_report_sales_user:
    path:     /sales-user
    defaults: { _controller: "MedicineBundle:Report:salesUser" }

medicine_report_sales_user_monthly:
    path:     /sales-user-monthly
    defaults: { _controller: "MedicineBundle:Report:monthlyUserSales" }

