medicine_stock:
    path:     /
    defaults: { _controller: "MedicineBundle:MedicineStock:index" }

medicine_stock_show:
    path:     /{id}/show
    defaults: { _controller: "MedicineBundle:MedicineStock:show" }

medicine_stock_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:MedicineStock:new" }

medicine_stock_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:MedicineStock:create" }
    methods:  POST

medicine_stock_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:MedicineStock:edit" }

medicine_stock_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:MedicineStock:update" }
    methods:  [POST, PUT]

medicine_stock_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:MedicineStock:delete" }

medicine_stock_status:
    path:     /{id}/status
    defaults: { _controller: "MedicineBundle:MedicineStock:status" }

medicine_stock_inline:
    path:     /inline-update
    defaults: { _controller: "MedicineBundle:MedicineStock:inlineUpdate" }

medicine_stock_details:
    path:     /{sku}/stock-details
    defaults: { _controller: "MedicineBundle:MedicineStock:inlineUpdate" }

medicine_stock_search:
    path:     /search
    defaults: { _controller: "MedicineBundle:MedicineStock:autoSearch" }
    options:
            expose: true

medicine_stock_name:
    path:      /{vendor}/vendor-name
    defaults: { _controller: "MedicineBundle:MedicineStock:searchVendorName" }
    options:
            expose: true