<?php

namespace Frontend\FrontentBundle\Service;

use Doctrine\ORM\EntityManager;
use Doctrine\Bundle\DoctrineBundle\Registry;
use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\Connection;
use Setting\Bundle\AppearanceBundle\Entity\Menu;
use Symfony\Component\Debug\Debug;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * RequestManager
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class MenuTreeManager

{

    /**
     * @var EntityManager
     */
    protected  $em;
    /**
     * @var \Doctrine\Bundle\DoctrineBundle\Registry
     */
    private $doctrine;

    public function  __construct(Registry $doctrine)
    {
        $this->doctrine = $doctrine;
        $this->em = $doctrine->getManager();
    }

    public function checkModule($slug)
    {
        $em = $this->em;

        $module = $em->getRepository('SettingToolBundle:Module')->findOneBy(array('menuSlug'=>$slug));
        $syndicateModule = $em->getRepository('SettingToolBundle:SyndicateModule')->findOneBy(array('menuSlug'=>$slug));


    }

    public function getMenuTreexx($arr,$subdomain)
    {

        // $subdomain ='mobile/'.$subdomainName;

        $value ='';
        $value .='<ul>';
        foreach ($arr as $val) {

            $menu = $val->getMenu()->getMenu();
            if (!empty($menu)) {
                $subIcon = (count($val->getChildren()) > 0 ) ? 1 : 2 ;
                if($subIcon == 1){
                    $value .= '<li><a href="/mobile/'.$subdomain.'/'.$val->getMenu()->getMenuSlug().'">' . $val->getMenu()->getMenu().'</a><span><i class="fa fa-caret-down"></i></span>';
                    $value .= $this->getMenuTree($val->getChildren(),$subdomain);
                }else{
                    $value .= '<li><a class="width-full" href="/mobile/'.$subdomain.'/'.$val->getMenu()->getMenuSlug().'">' . $val->getMenu()->getMenu().'</a>';
                }

                $value .= '</li>';
            } else {
                $value .= '<li><a href="/mobile/'.$subdomain.'/'.$val->getMenu()->getMenuSlug().'">'.$val->getMenu()->getMenu() . '</a></li>';
            }
        }
        $value .='</ul>';

        return $value;

    }

    public function getMenuTree($arr,$subdomain,$device ='')
    {

        $value ='';
            $value .='<ul>';
            $prefix = '';
        foreach ($arr as $val) {

            $menu = $val->getMenu()->getMenu();
            
            if (!empty($menu)) {
                $subIcon = (count($val->getChildren()) > 0 ) ? 1 : 2 ;
                if($subIcon == 1){
                    $value .= '<li><a href="/'.$val->getMenu()->getSlug().'">' . $val->getMenu()->getMenu().'</a>';
                    $value .= $this->getMenuTree($val->getChildren(),$subdomain,$device);
                }else{
                    $value .= '<li><a href="/'.$val->getMenu()->getSlug().'">' . $val->getMenu()->getMenu().'</a>';
                }
                $value .= '</li>';
            } else {
                $value .= '<li><a href="/'.$val->getMenu()->getSlug().'">'.$val->getMenu()->getMenu() . '</a></li>';
            }
        }
        $value .='</ul>';

        return $value;

    }


    public function getEcommerceFooterMenuTree($arr,$subdomain,$device ='')
    {

        $value ='';
        $value .='<ul>';
        $prefix = '';
        foreach ($arr as $val) {

            $menu = $val->getMenu()->getMenu();
            if (!empty($menu)) {
                $subIcon = (count($val->getChildren()) > 0 ) ? 1 : 2 ;
                if($subIcon == 1){
                    $value .= '<li><a href="/'.$val->getMenu()->getSlug().'">' . $val->getMenu()->getMenu().'</a>';
                    $value .= $this->getMenuTree($val->getChildren(),$subdomain,$device);
                }else{
                    $value .= '<li><a href="/'.$val->getMenu()->getSlug().'">' . $val->getMenu()->getMenu().'</a>';
                }
                $value .= '</li>';
            } else {
                $value .= '<li><a href="/'.$val->getMenu()->getSlug().'">'.$val->getMenu()->getMenu() . '</a></li>';
            }
        }
        $value .='</ul>';

        return $value;

    }

    public function getMobileMenuTree($arr,$subdomain,$device ='')
    {

        $value ='';
        $value .='<ul>';
        $prefix = '/web-builder/mobile/'.$subdomain.'/';
        foreach ($arr as $val) {

            $menu = $val->getMenu()->getMenu();
            if (!empty($menu)) {
                $subIcon = (count($val->getChildren()) > 0 ) ? 1 : 2 ;
                if($subIcon == 1){
                    $value .= '<li><a href="'.$prefix.$val->getMenu()->getSlug().'">' . $val->getMenu()->getMenu().'</a>';
                    $value .= $this->getMenuTree($val->getChildren(),$subdomain,$device);
                }else{
                    $value .= '<li><a href="'.$prefix.$val->getMenu()->getSlug().'">' . $val->getMenu()->getMenu().'</a>';
                }

                $value .= '</li>';
            } else {
                $value .= '<li><a href="'.$prefix.$val->getMenu()->getSlug().'">'.$val->getMenu()->getMenu() . '</a></li>';
            }
        }
        $value .='</ul>';

        return $value;

    }

    public function getFooterMenu($menus,$subdomain,$device ='')
    {

        $value ='<ul class="list-footer">';
        $prefix = $subdomain;
        foreach ($menus as $val) {
            $menu = $val->getMenu()->getMenu();
            if (!empty($menu)) {
                $value .= '<li><a href="/'. $val->getMenu()->getSlug() . '"><i class="fa fa-angle-right"></i> ' . $val->getMenu()->getMenu() . '</a></li>';
            }
        }
        $value .='</ul>';

        return $value;

    }



    public function getModuleTheme($menu)
    {


        /* this condition return module,syndicate module , page ,syndicate functional theme return. */
        $moduleTheme = false;

        if($menu->getModule()){
            $moduleTheme = $menu->getModule()->getModuleClass();
        }elseif($menu->getSyndicateModule()){
            $moduleTheme = $menu->getSyndicateModule()->getModuleClass();
        }elseif($menu->getSyndicate()){
            $moduleTheme = 'SyndicateContent';
        }

        return $moduleTheme;


    }

    public function getCheckModule($menu)
    {


        /* this condition return module,syndicate module , page ,syndicate functional theme return. */
        $moduleTheme = false;

        if($menu->getModule()){
            $moduleTheme = $menu->getModule()->getModuleClass();
        }elseif($menu->getSyndicateModule()){
            $moduleTheme = $menu->getSyndicateModule()->getModuleClass();
        }elseif($menu->getSyndicate()){
            $moduleTheme = 'SyndicateContent';
        }

        return $moduleTheme;


    }



}
