smssender:
    path:     /
    defaults: { _controller: "SettingToolBundle:SmsSender:index" }

smssender_delete:
    path:     /delete
    defaults: { _controller: "SettingToolBundle:SmsSender:delete" }
