templatecustomize:
    path:     /
    defaults: { _controller: "SettingToolBundle:TemplateCustomize:index" }

templatecustomize_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:TemplateCustomize:show" }

templatecustomize_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:TemplateCustomize:new" }

templatecustomize_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:TemplateCustomize:create" }
    methods:  POST

templatecustomize_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:TemplateCustomize:edit" }

templatecustomize_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:TemplateCustomize:update" }
    methods:  [POST, PUT]

templatecustomize_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:TemplateCustomize:delete" }
    methods:  [POST, DELETE]
