desktop:
    path:     /
    defaults: { _controller: DesktopBundle:Default:index }

desktop_home:
    path:     /{subdomain}
    defaults: { _controller: DesktopBundle:Default:index }

desktop_product_details:
    path:    /{subdomain}/product/{product}/product-details
    defaults: { _controller: DesktopBundle:Product:productDetails }

desktop_product:
    path:     /{subdomain}/product
    defaults: { _controller: DesktopBundle:Product:product }


desktop_product_add_cart:
    path:    /{subdomain}/{id}/add-cart
    defaults: { _controller: DesktopBundle:Product:productAddCart }

blog_message:
    path:     /{subdomain}/{module}/{slug}
    defaults: { _controller: DesktopBundle:Page:blogSubmit }
    requirements: { _method: post }

admission_message:
    path:     /{subdomain}/{module}/{slug}
    defaults: { _controller: DesktopBundle:Page:admissionSubmit }
    requirements: { _method: post }

desktop_blogs:
    path:     /{subdomain}/blogs
    defaults: { _controller: DesktopBundle:Module:blogs }

desktop_contact:
    path:     /{subdomain}/contact
    defaults: { _controller: DesktopBundle:Default:contact }

desktop_sms:
    path:     /{subdomain}/sms
    defaults: { _controller: DesktopBundle:Default:sms}

desktop_email_receive:
    path:     /{subdomain}/email-receive
    defaults: { _controller: DesktopBundle:Receive:emailReceiving }
    requirements: { _method: post }

desktop_sms_receive:
    path:     /{subdomain}/sms-receive
    defaults: { _controller: DesktopBundle:Receive:smsReceiving }

desktop_maps:
    path:     /{subdomain}/maps
    defaults: { _controller: DesktopBundle:Default:maps }

desktop_sms_send:
    path:     /{subdomain}/{slug}
    defaults: { _controller: DesktopBundle:Page:smsSending }
    requirements: { _method: post }

desktop_content:
    path:     /{subdomain}/{slug}
    defaults: { _controller: DesktopBundle:Page:index }

desktop_module:
    path:     /{subdomain}/{module}/{slug}
    defaults: { _controller: DesktopBundle:Module:index }




