services:
#    desktop.example:
#        class: Desktop\Bundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

      device.toolManageRepo:
          class: Desktop\Bundle\Service\MobileDetect
          arguments: [@doctrine]