setting_appearance_feature:
    resource: "@SettingAppearanceBundle/Resources/config/routing/appearancefeature.yml"
    prefix:   /domain/feature

setting_appearance_featurewidget:
    resource: "@SettingAppearanceBundle/Resources/config/routing/appearancefeaturewidget.yml"
    prefix:   /domain/feature-widget

setting_appearance_menuwidget:
    resource: "@SettingAppearanceBundle/Resources/config/routing/appearancemenuwidget.yml"
    prefix:   /domain/menu-widget

setting_appearance_featurewidgetitem:
    resource: "@SettingAppearanceBundle/Resources/config/routing/appearancefeaturewidgetitem.yml"
    prefix:   /domain/sidebar-widget-item

setting_appearance_sidebarwidget:
    resource: "@SettingAppearanceBundle/Resources/config/routing/sidebarwidget.yml"
    prefix:   /domain/sidebar-widget

setting_appearance_appearancecategory:
    resource: "@SettingAppearanceBundle/Resources/config/routing/featurecategory.yml"
    prefix:   /e-commerce/feature-category

setting_appearance_appearancebrand:
    resource: "@SettingAppearanceBundle/Resources/config/routing/featurebrand.yml"
    prefix:   /e-commerce/feature-brand

setting_appearance_ecommercemenu:
    resource: "@SettingAppearanceBundle/Resources/config/routing/ecommercemenu.yml"
    prefix:   /domain/ecommerce-menu

setting_appearance_megamenu:
    resource: "@SettingAppearanceBundle/Resources/config/routing/megamenu.yml"
    prefix:   /domain/mega-menu

SettingAppearanceBundle_menu:
    resource: "@SettingAppearanceBundle/Resources/config/routing/menu.yml"
    prefix:   /domain/menu

SettingAppearanceBundle_menugroup:
    resource: "@SettingAppearanceBundle/Resources/config/routing/menugroup.yml"
    prefix:   /domain/menugroup

SettingAppearanceBundle_menugrouping:
    resource: "@SettingAppearanceBundle/Resources/config/routing/menugrouping.yml"
    prefix:   /domain/menugrouping

setting_appearance_menucustom:
    resource: "@SettingAppearanceBundle/Resources/config/routing/menucustom.yml"
    prefix:   /admin/menucustom