serviceinvoice:
    path:     /
    defaults: { _controller: "ServiceBundle:ServiceInvoice:index" }

serviceinvoice_show:
    path:     /{id}/show
    defaults: { _controller: "ServiceBundle:ServiceInvoice:show" }

serviceinvoice_new:
    path:     /new
    defaults: { _controller: "ServiceBundle:ServiceInvoice:new" }

serviceinvoice_create:
    path:     /create
    defaults: { _controller: "ServiceBundle:ServiceInvoice:create" }
    methods:  POST

serviceinvoice_generate:
    path:     /{id}/generate
    defaults: { _controller: "ServiceBundle:ServiceInvoice:generate" }

serviceinvoice_edit:
    path:     /{id}/edit
    defaults: { _controller: "ServiceBundle:ServiceInvoice:edit" }

serviceinvoice_update:
    path:     /{id}/update
    defaults: { _controller: "ServiceBundle:ServiceInvoice:update" }
    methods:  [POST, PUT]

serviceinvoice_delete:
    path:     /{id}/delete
    defaults: { _controller: "ServiceBundle:ServiceInvoice:delete" }
    methods:  [POST, DELETE]
