syndicate_component_studyabroad:
    resource: "@SyndicateComponentBundle/Resources/config/routing/studyabroad.yml"
    prefix:   /studyabroad

syndicate_component_tutorial-author:
    resource: "@SyndicateComponentBundle/Resources/config/routing/tutorial.yml"
    prefix:   /tutorial-author

syndicate_component_tutor:
    resource: "@SyndicateComponentBundle/Resources/config/routing/tutor.yml"
    prefix:   /tutor

syndicate_component_scholarship:
    resource: "@SyndicateComponentBundle/Resources/config/routing/scholarship.yml"
    prefix:   /scholarship

syndicate_component_homepage:
    path:     /hello/{name}
    defaults: { _controller: SyndicateComponentBundle:Default:index }

SyndicateComponentBundle_education:
    resource: "@SyndicateComponentBundle/Resources/config/routing/education.yml"
    prefix:   /education

SyndicateComponentBundle_vendor:
    resource: "@SyndicateComponentBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor