sylius_cart:
    resolver: app.cart_item_resolver # The id of our newly created service.
    classes: ~ # This key can be empty but it must be present in the configuration.

sylius_order:
    driver: doctrine/orm # Configure the doctrine orm driver used in documentation.
    classes:
        order_item:
            model: Frontend\FrontentBundle\Entity\CartItem # If you have created a custom CartItem entity.

sylius_money: ~