restaurant_invoice:
    path:     /
    defaults: { _controller: "RestaurantBundle:Invoice:index" }

restaurant_invoice_show:
    path:     /{id}/show
    defaults: { _controller: "RestaurantBundle:Invoice:show" }

restaurant_invoice_new:
    path:     /new
    defaults: { _controller: "RestaurantBundle:Invoice:new" }


restaurant_invoice_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestaurantBundle:Invoice:edit" }

restaurant_invoice_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "RestaurantBundle:Invoice:particularSearch" }


restaurant_invoice_particular_add:
    path:     /{invoice}/particular-add
    defaults: { _controller: "RestaurantBundle:Invoice:addParticular" }
    methods:  POST
    options:
            expose: true

restaurant_invoice_discount_update:
    path:     /invoice/invoice-dicount-update
    defaults: { _controller: "RestaurantBundle:Invoice:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

restaurant_invoice_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "RestaurantBundle:Invoice:approve" }
    methods:  POST
    options:
            expose: true

restaurant_invoice_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantBundle:Invoice:update" }
    methods:  [POST, PUT]

restaurant_invoice_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestaurantBundle:Invoice:delete" }

restaurant_invoice_reverse:
    path:     /{invoice}/invoice-reverse-create
    defaults: { _controller: "RestaurantBundle:Invoice:pathologicalInvoiceReverse" }

restaurant_invoice_reverse_show:
    path:     /{id}/invoice-reverse-show
    defaults: { _controller: "RestaurantBundle:Invoice:InvoiceReverseShow" }

restaurant_invoice_discount_delete:
    path:     /{id}/discount-delete
    defaults: { _controller: "RestaurantBundle:Invoice:discountDelete" }

restaurant_invoice_confirm:
    path:     /{id}/invoice-confirm
    defaults: { _controller: "RestaurantBundle:Invoice:confirm" }

restaurant_invoice_particular_delete:
    path:     /{invoice}/{id}/particular-delete
    defaults: { _controller: "RestaurantBundle:Invoice:invoiceParticularDelete" }

restaurant_invoice_print_invoice:
    path:     /{id}/print
    defaults: { _controller: "RestaurantBundle:Invoice:invoicePrint" }

restaurant_invoice_process_update:
    path:     /hms-invoice/upadte-process
    defaults: { _controller: "RestaurantBundle:Invoice:invoiceProcessUpdate" }
    methods:  POST
    options:
            expose: true

restaurant_invoice_status_select:
    path:     /invoice-status-select
    defaults: { _controller: "RestaurantBundle:Invoice:statusSelect" }
    options:
           expose: true

restaurant_invoice_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "RestaurantBundle:Invoice:deleteEmptyInvoice" }

restaurant_invoice_customer_details:
    path:     /invoice-patient-details
    defaults: { _controller: "DomainUserBundle:CustomerHms:details" }
    methods:  POST
    options:
           expose: true

restaurant_invoice_pos:
    path:     /{invoice}/invoice-pos-print
    defaults: { _controller: "RestaurantBundle:Invoice:PosPrint" }
    methods:  [PUT,POST]
    options:
            expose: true

restaurant_invoice_kitchen:
    path:     /{invoice}/invoice-kitchen-print
    defaults: { _controller: "RestaurantBundle:Invoice:KitchenPrint" }
    options:
            expose: true

restaurant_invoice_token_check:
    path:      /invoice-token-check
    defaults: { _controller: "RestaurantBundle:Invoice:checkTokenBooking" }
    methods:  [POST]
    options:
            expose: true