restaurant_production_edit:
    path:     /{id}/
    defaults: { _controller: "RestaurantBundle:Production:production" }

restaurant_production_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantBundle:Production:productionUpdate" }
    methods:  [POST, PUT]


restaurant_production_delete:
    path:     /{product}/{id}/delete
    defaults: { _controller: "RestaurantBundle:Production:productionElementDelete" }

restaurant_production_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "RestaurantBundle:Production:particularSearch" }


restaurant_production_particular_add:
    path:     /{id}/particular-add
    defaults: { _controller: "RestaurantBundle:Production:addParticular" }
    methods:  POST
    options:
            expose: true

restaurant_production_valueadded:
    path:     /{id}/item-value-add
    defaults: { _controller: "RestaurantBundle:Production:itemValueAdd" }
    methods:  GET
    options:
            expose: true

