restaurant_report_sales_summary:
    path:     /sales-summary
    defaults: { _controller: "RestaurantBundle:Report:salesSummary" }

restaurant_report_sales_details:
    path:     /sales-details
    defaults: { _controller: "RestaurantBundle:Report:salesDetails" }

restaurant_report_sales_service:
    path:     /service-wise-sales
    defaults: { _controller: "RestaurantBundle:Report:serviceBaseSummary" }

restaurant_report_purchase_summary:
    path:     /purchase-summary
    defaults: { _controller: "RestaurantBundle:Report:purchaseSummary" }

restaurant_report_stock:
    path:     /stock-summary
    defaults: { _controller: "RestaurantBundle:Report:purchaseSummary" }

