attendance:
    path:     /
    defaults: { _controller: "HumanResourceBundle:Attendance:index" }

attendance_user:
    path:     /{user}/employee
    defaults: { _controller: "HumanResourceBundle:Attendance:employeeDetails" }

weekend_update:
    path:     /{id}/update
    defaults: { _controller: "HumanResourceBundle:Weekend:update" }
    methods:  [POST, PUT]

