<?php

namespace Appstore\Bundle\MedicineBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * GenericRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicineGenericRepository extends EntityRepository
{
}
