<?php

namespace Appstore\Bundle\MedicineBundle\Repository;


use Appstore\Bundle\MedicineBundle\Entity\MedicineBrand;
use Doctrine\ORM\EntityRepository;

/**
 * MedicineCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicineBrandRepository extends EntityRepository
{
    public function updateMedicine()
    {
        $results = $this->findAll();

        /** @var $row MedicineBrand */
        foreach ($results as $row ){
            $company = $this->_em->getRepository('MedicineBundle:MedicineCompany')->findOneBy(array('companyId'=> $row->getCompanyId()));
            $generic = $this->_em->getRepository('MedicineBundle:MedicineGeneric')->findOneBy(array('genericId'=> $row->getGenericId()));
            $row->setMedicineGeneric($generic);
            $row->setMedicineCompany($company);
            $this->_em->persist($row);
            $this->_em->flush();

        }

    }

    public function searchMedicineAutoComplete($q)
    {
        $query = $this->createQueryBuilder('e');
        $query->join('e.medicineGeneric','g');
        $query->join('e.medicineCompany','c');
        $query->select('e.id as id');
        $query->addSelect('CONCAT(e.medicineForm, \' \', e.name, \' \', g.name, \' \', e.strength, \' \', c.name) AS text');
        $query->where($query->expr()->like("e.name", "'$q%'"  ));
        $query->groupBy('e.id');
        $query->orderBy('e.name', 'ASC');
        $query->setMaxResults( '50' );
        return $query->getQuery()->getResult();

    }

    public function searchGenericAutoComplete($q)
    {
        $query = $this->createQueryBuilder('e');
        $query->join('e.medicineGeneric','g');
        $query->join('e.medicineCompany','c');
        $query->select('e.id as id');
        $query->addSelect('CONCAT(e.medicineForm, \' \', e.name, \' \', e.strength, \' \', g.name, \' \', c.name) AS text');
        $query->where($query->expr()->like("g.name", "'$q%'"  ));
        $query->groupBy('e.id');
        $query->orderBy('e.name', 'ASC');
        $query->setMaxResults( '50' );
        return $query->getQuery()->getResult();

    }
}
