site_domain_control:
    resource: "dynamic/sites.yml"
    type:     rest

election:
    resource: "@ElectionBundle/Resources/config/routing.yml"
    prefix:   /election

hotel:
    resource: "@HotelBundle/Resources/config/routing.yml"
    prefix:   /hotel-restaurant

doctor_prescription:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing.yml"
    prefix:   /doctor-prescription

education:
    resource: "@EducationBundle/Resources/config/routing.yml"
    prefix:   /education

business:
    resource: "@BusinessBundle/Resources/config/routing.yml"
    prefix:   /business

office:
    resource: "@OfficeBundle/Resources/config/routing.yml"
    prefix:   /office

medicine:
    resource: "@MedicineBundle/Resources/config/routing.yml"
    prefix:   /medicine

appstore_dms:
    resource: "@DmsBundle/Resources/config/routing.yml"
    prefix:   /dms

appstore_restaurant:
    resource: "@RestaurantBundle/Resources/config/routing.yml"
    prefix:   /restaurant

human_resource:
    resource: "@HumanResourceBundle/Resources/config/routing.yml"
    prefix:   /human-resource

hospital:
    resource: "@HospitalBundle/Resources/config/routing.yml"
    prefix:   /hms

core_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"

customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix:   /customer

ims:
    resource: "@ImsBundle/Resources/config/routing.yml"
    prefix:   /

config:
    resource: "@ConfigBundle/Resources/config/routing.yml"
    prefix:   /

accounting:
    resource: "@AccountingBundle/Resources/config/routing.yml"
    prefix:   /

domain_user:
    resource: "@DomainUserBundle/Resources/config/routing.yml"
    prefix:   /

appstore_billing:
    resource: "@AppstoreBillingBundle/Resources/config/routing.yml"
    prefix:   /

appstore_inventory:
    resource: "@InventoryBundle/Resources/config/routing.yml"
    prefix:   /inventory

appstore_ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /

setting_advertisment:
    resource: "@SettingAdvertismentBundle/Resources/config/routing.yml"
    prefix:   /

product_product:
    resource: "@ProductProductBundle/Resources/config/routing.yml"
    prefix:   /admin

syndicate_component:
    resource: "@SyndicateComponentBundle/Resources/config/routing.yml"
    prefix:   /admin

setting_tool:
    resource: "@SettingToolBundle/Resources/config/routing.yml"
    prefix:   /

setting_content:
    resource: "@SettingContentBundle/Resources/config/routing.yml"
    prefix:   /

setting_appearance:
    resource: "@SettingAppearanceBundle/Resources/config/routing.yml"
    prefix:   /

setting_media:
    resource: "@SettingMediaBundle/Resources/config/routing.yml"
    prefix:   /

setting_location:
    resource: "@SettingLocationBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

domain_control:
    resource: "@XiideaDomainBundle/Resources/config/routing.yml"
    type:     rest

bindu:
    resource: "@BinduBundle/Resources/config/main.yml"
    prefix:   /