security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:

        ROLE_CUSTOMER:                      [ROLE_USER]
        ROLE_VENDOR:                        [ROLE_USER]
        ROLE_MANAGER:                       [ROLE_USER]
        ROLE_DOMAIN_CUSTOMER:               [ROLE_USER]
        ROLE_DOMAIN_USER:                   [ROLE_USER]

        # THIS IS PART OF WEBSITE MANAGE

        ROLE_WEBSITE:                               [ROLE_WEBSITE]
        ROLE_DOMAIN_WEBSITE:                        [ROLE_WEBSITE,ROLE_DOMAIN_WEBSITE]
        ROLE_DOMAIN_WEBSITE_FINANCE:                [ROLE_WEBSITE,ROLE_DOMAIN_WEBSITE_FINANCE]
        ROLE_DOMAIN_WEBSITE_SETTING:                [ROLE_WEBSITE,ROLE_DOMAIN_WEBSITE_SETTING]
        ROLE_DOMAIN_WEBSITE_CUSTOMER:               [ROLE_WEBSITE,ROLE_DOMAIN_WEBSITE_CUSTOMER]
        ROLE_DOMAIN_WEBSITE_MANAGER:                [ROLE_DOMAIN_WEBSITE,ROLE_DOMAIN_SETTING,ROLE_DOMAIN_CUSTOMER]

        # THIS IS PART OF FINANCE MANAGE

        ROLE_FINANCE:                               [ROLE_FINANCE]
        ROLE_DOMAIN_FINANCE_TRANSACTION:            [ROLE_FINANCE,ROLE_DOMAIN_FINANCE_TRANSACTION]
        ROLE_DOMAIN_FINANCE_EXPENDITURE:            [ROLE_FINANCE,ROLE_DOMAIN_FINANCE_EXPENDITURE]
        ROLE_DOMAIN_FINANCE_PURCHASE:               [ROLE_FINANCE,ROLE_DOMAIN_FINANCE_PURCHASE]
        ROLE_DOMAIN_FINANCE_SALES:                  [ROLE_FINANCE,ROLE_DOMAIN_FINANCE_SALES]
        ROLE_DOMAIN_FINANCE_BANK:                   [ROLE_FINANCE,ROLE_DOMAIN_FINANCE_BANK]
        ROLE_DOMAIN_FINANCE_PETTY_CASH:             [ROLE_FINANCE,ROLE_DOMAIN_FINANCE_PETTY_CASH]
        ROLE_DOMAIN_FINANCE_JOURNAL:                [ROLE_FINANCE,ROLE_DOMAIN_FINANCE_JOURNAL]
        ROLE_DOMAIN_FINANCE_MANAGER:                [ROLE_FINANCE,ROLE_DOMAIN_FINANCE_TRANSACTION,ROLE_DOMAIN_FINANCE_EXPENDITURE,ROLE_DOMAIN_FINANCE_PURCHASE,ROLE_DOMAIN_FINANCE_SALES,ROLE_DOMAIN_FINANCE_BANK,ROLE_DOMAIN_FINANCE_PETTY_CASH,ROLE_DOMAIN_FINANCE_JOURNAL]
        ROLE_DOMAIN_FINANCE_APPROVER:               [ROLE_DOMAIN_FINANCE_MANAGER,ROLE_DOMAIN_FINANCE_APPROVER]


        # THIS IS PART OF HR and PAYROLL MANAGE

        ROLE_HR:                                    [ROLE_HR]
        ROLE_DOMAIN_HR_EMPLOYEE_MANAGER:            [ROLE_HR,ROLE_DOMAIN_HR_EMPLOYEE_MANAGER]
        ROLE_PAYROLL:                               [ROLE_PAYROLL]
        ROLE_PAYROLL_SALARY:                        [ROLE_PAYROLL,ROLE_PAYROLL_SALARY]
        ROLE_PAYROLL_SALARY_PAYMENT:                [ROLE_PAYROLL,ROLE_PAYROLL_SALARY_PAYMENT]
        ROLE_PAYROLL_SALARY_SETTING:                [ROLE_PAYROLL,ROLE_PAYROLL_SALARY_SETTING]
        ROLE_PAYROLL_MANAGER:                       [ROLE_DOMAIN_HR_EMPLOYEE_MANAGE,ROLE_PAYROLL_SALARY,ROLE_PAYROLL_SALARY_PAYMENT,ROLE_PAYROLL_SALARY_SETTING]
        ROLE_PAYROLL_MANAGER_APPROVER:              [ROLE_PAYROLL_MANAGER,ROLE_PAYROLL_MANAGER_APPROVER]


        # THIS IS PART OF INVENTORY MANAGE

        ROLE_INVENTORY:                             [ROLE_INVENTORY]
        ROLE_DOMAIN_INVENTORY_STOCK:                [ROLE_INVENTORY,ROLE_DOMAIN_INVENTORY_STOCK]
        ROLE_DOMAIN_INVENTORY_SETTING:              [ROLE_INVENTORY,ROLE_DOMAIN_INVENTORY_SETTING]
        ROLE_DOMAIN_INVENTORY_CONFIG:               [ROLE_INVENTORY,ROLE_DOMAIN_INVENTORY_CONFIG]
        ROLE_DOMAIN_INVENTORY_PURCHASE:             [ROLE_DOMAIN_INVENTORY_STOCK,ROLE_DOMAIN_INVENTORY_SETTING,ROLE_DOMAIN_INVENTORY_PURCHASE,ROLE_DOMAIN_FINANCE_PURCHASE]
        ROLE_DOMAIN_CUSTOMER:                       [ROLE_INVENTORY]
        ROLE_DOMAIN_INVENTORY_SALES:                [ROLE_INVENTORY,ROLE_DOMAIN_CUSTOMER,ROLE_DOMAIN_CUSTOMER,ROLE_DOMAIN_INVENTORY_SALES,ROLE_DOMAIN_FINANCE_SALES]

        # THIS IS ECOMMERCE PART

        ROLE_ECOMMERCE:                             [ROLE_ECOMMERCE]
        ROLE_DOMAIN_INVENTORY_ECOMMERCE:            [ROLE_ECOMMERCE,ROLE_INVENTORY,ROLE_DOMAIN_CUSTOMER,ROLE_DOMAIN_INVENTORY_ECOMMERCE]
        ROLE_DOMAIN_INVENTORY_ECOMMERCE_MANAGER:    [ROLE_ECOMMERCE,ROLE_INVENTORY,ROLE_DOMAIN_INVENTORY_ECOMMERCE,ROLE_DOMAIN_INVENTORY_ECOMMERCE_MANAGER]

        ROLE_FOOD:                                  [ROLE_FOOD]
        ROLE_DOMAIN_FOOD:                           [ROLE_FOOD,ROLE_DOMAIN_FOOD]
        ROLE_DOMAIN_FOOD_MANAGER:                   [ROLE_DOMAIN_FOOD,ROLE_DOMAIN_FOOD_MANAGER]

        ROLE_GOODS:                                 [ROLE_GOODS]
        ROLE_DOMAIN_GOODS:                          [ROLE_GOODS,ROLE_DOMAIN_GOODS]
        ROLE_DOMAIN_GOODS_MANAGER:                  [ROLE_DOMAIN_GOODS,ROLE_DOMAIN_GOODS_MANAGER]


        ROLE_DOMAIN_INVENTORY_MANAGER:              [ROLE_DOMAIN_INVENTORY_CONFIG,ROLE_DOMAIN_INVENTORY_PURCHASE,ROLE_DOMAIN_INVENTORY_SALES,ROLE_DOMAIN_INVENTORY_ECOMMERCE_MANAGER]
        ROLE_DOMAIN_INVENTORY_APPROVE:              [ROLE_DOMAIN_INVENTORY_MANAGER,ROLE_DOMAIN_INVENTORY_APPROVE]

        # THIS IS PART OF MAIN DOMAIN MANAGE

        ROLE_DOMAIN_MANAGER:                        [ROLE_DOMAIN,ROLE_DOMAIN_WEBSITE_MANAGER,ROLE_DOMAIN_MANAGER,ROLE_DOMAIN_FINANCE_APPROVER,ROLE_DOMAIN_INVENTORY_APPROVE,ROLE_DOMAIN_INVENTORY_ECOMMERCE_MANAGER]
        ROLE_DOMAIN:                                [ROLE_DOMAIN,ROLE_DOMAIN_MANAGER,ROLE_DOMAIN_SETTING,ROLE_DOMAIN_HR_EMPLOYEE_MANAGER,ROLE_PAYROLL_MANAGER_APPROVER,ROLE_FOOD,ROLE_DOMAIN_GOODS_MANAGER]

        ROLE_APPROVAL_ADMIN:                        [ROLE_OPERATION_APPROVE]
        ROLE_ADMIN:                                 [ROLE_ADMIN,ROLE_DOMAIN]
        ROLE_SUPER_ADMIN:                           [ROLE_CUSTOMER, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: homepage
                always_use_default_target_path: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$,             role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,              role: ROLE_SUPER_ADMIN }
        - { path: ^/domain,             role: ROLE_DOMAIN }
        - { path: ^/website,            role: ROLE_WEBSITE }
        - { path: ^/finance,            role: ROLE_FINANCE }
        - { path: ^/hr,                 role: ROLE_HR }
        - { path: ^/payroll,            role: ROLE_PAYROLL }
        - { path: ^/inventory,          role: ROLE_INVENTORY }
        - { path: ^/vendor,             role: ROLE_DOMAIN }
        - { path: ^/web-builder/build,  role: ROLE_DOMAIN }
        - { path: ^/customer,           role: ROLE_CUSTOMER }
        - { path: ^/user,               role: ROLE_USER }
        - { path: ^/general,            role: ROLE_USER }
        - { path: ^/ecommerce,          role: ROLE_ECOMMERCE }
        - { path: ^/food,               role: ROLE_FOOD }
        - { path: ^/goods,              role: ROLE_GOODS }
        - { path: ^/,                   role: IS_AUTHENTICATED_ANONYMOUSLY }
