security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:

        ROLE_CUSTOMER:                                  [ROLE_USER]
        ROLE_AGENT:                                     [ROLE_AGENT]
        ROLE_VENDOR:                                    [ROLE_USER]
        ROLE_MANAGER:                                   [ROLE_USER]
        ROLE_ADMIN_OPERATION_USER:                      [ROLE_USER]
        ROLE_ADMIN_OPERATION_MANAGER:                   [ROLE_USER]
        ROLE_DOMAIN_CUSTOMER:                           [ROLE_USER]
        ROLE_DOMAIN_USER:                               [ROLE_USER]
        ROLE_DOMAIN_USER:                               [ROLE_DOAMIN]
        ROLE_WEBSITE:                                   [ROLE_WEBSITE]
        ROLE_APPEARANCE:                                [ROLE_APPEARANCE]
        ROLE_HMS:                                       [ROLE_HMS,ROLE_MEDICINE]
        ROLE_DMS:                                       [ROLE_DMS,ROLE_MEDICINE]
        ROLE_MEDICINE:                                  [ROLE_MEDICINE]
        ROLE_RESTAURANT:                                [ROLE_RESTAURANT]
        ROLE_CRM:                                       [ROLE_DOMAIN,ROLE_INVENTORY,ROLE_HR,ROLE_DPS,ROLE_RESTAURANT,ROLE_MEDICINE,ROLE_WEBSITE,ROLE_DOAMIN,ROLE_BUSINESS,ROLE_OFFICE]
        ROLE_CRM_MANAGER:                               [ROLE_CRM,ROLE_CRM_MANAGER]

        # THIS IS PART OF WEBSITE MANAGE


        ROLE_DOMAIN_WEBSITE_CUSTOMER:                   [ROLE_DOMAIN_WEBSITE_CUSTOMER,ROLE_WEBSITE]
        ROLE_DOMAIN_WEBSITE_MANAGER:                    [ROLE_DOMAIN_WEBSITE_MANAGER]
        ROLE_DOMAIN_WEBSITE_SETTING:                    [ROLE_DOMAIN_WEBSITE_SETTING,ROLE_APPEARANCE]
        ROLE_DOMAIN_WEBSITE:                            [ROLE_APPEARANCE,ROLE_WEBSITE,ROLE_DOMAIN_WEBSITE_CUSTOMER,ROLE_DOMAIN_WEBSITE_SETTING,ROLE_DOMAIN_WEBSITE_MANAGER,ROLE_DOMAIN_USER,ROLE_ACCOUNTING]

        # THIS IS PART OF ACCOUNTING MANAGE

        ROLE_ACCOUNTING:                                [ROLE_ACCOUNTING]
        ROLE_DOMAIN_ACCOUNTING_REPORT:                  [ROLE_DOMAIN_ACCOUNTING_REPORT]
        ROLE_DOMAIN_ACCOUNTING_TRANSACTION:             [ROLE_DOMAIN_ACCOUNTING_TRANSACTION]
        ROLE_DOMAIN_ACCOUNTING_EXPENDITURE:             [ROLE_DOMAIN_ACCOUNTING_EXPENDITURE]
        ROLE_DOMAIN_ACCOUNTING_PURCHASE:                [ROLE_DOMAIN_ACCOUNTING_PURCHASE]
        ROLE_DOMAIN_ACCOUNTING_SALES:                   [ROLE_DOMAIN_ACCOUNTING_SALES]
        ROLE_DOMAIN_ACCOUNTING_ECOMMERCE:               [ROLE_DOMAIN_ACCOUNTING_ECOMMERCE]
        ROLE_DOMAIN_ACCOUNTING_BANK:                    [ROLE_DOMAIN_ACCOUNTING_BANK]
        ROLE_DOMAIN_ACCOUNTING_PETTY_CASH:              [ROLE_DOMAIN_ACCOUNTING_PETTY_CASH]
        ROLE_DOMAIN_ACCOUNTING_JOURNAL:                 [ROLE_DOMAIN_ACCOUNTING_JOURNAL]
        ROLE_DOMAIN_ACCOUNTING_APPROVAL:                [ROLE_DOMAIN_ACCOUNTING_APPROVAL]
        ROLE_DOMAIN_ACCOUNTING_CONFIG:                  [ROLE_DOMAIN_ACCOUNTING_CONFIG]
        ROLE_DOMAIN_ACCOUNTING_DELETE:                  [ROLE_DOMAIN_ACCOUNTING_DELETE]
        ROLE_DOMAIN_ACCOUNT_REVERSE:                    [ROLE_DOMAIN_ACCOUNT_REVERSE]
        ROLE_DOMAIN_ACCOUNTING:                         [ROLE_ACCOUNTING,ROLE_DOMAIN_ACCOUNTING_REPORT,ROLE_DOMAIN_ACCOUNTING_JOURNAL,ROLE_DOMAIN_ACCOUNTING_PETTY_CASH,ROLE_DOMAIN_ACCOUNTING_BANK,ROLE_DOMAIN_ACCOUNTING_SALES,ROLE_DOMAIN_ACCOUNTING_TRANSACTION,ROLE_DOMAIN_ACCOUNTING_EXPENDITURE,ROLE_DOMAIN_ACCOUNTING_PURCHASE,ROLE_DOMAIN_ACCOUNTING_APPROVAL,ROLE_DOMAIN_ACCOUNTING_CONFIG,ROLE_APP_SETTING,ROLE_DOMAIN_ACCOUNT_REVERSE]


        # THIS IS PART OF OFFICE MANAGEMENT

        ROLE_ELECTION:                                  [ROLE_ELECTION]
        ROLE_ELECTION_STAFF:                            [ROLE_ELECTION,ROLE_ELECTION_STAFF]
        ROLE_ELECTION_MANAGER:                          [ROLE_ELECTION,ROLE_ELECTION_STAFF,ROLE_ELECTION_MANAGER]
        ROLE_ELECTION_ADMIN:                            [ROLE_ELECTION_MANAGER,ROLE_ELECTION_ADMIN]

        # THIS IS PART OF OFFICE MANAGEMENT

        ROLE_OFFICE:                                    [ROLE_OFFICE]
        ROLE_OFFICE_STAFF:                              [ROLE_OFFICE,ROLE_OFFICE_STAFF]
        ROLE_OFFICE_INVOICE:                            [ROLE_OFFICE,ROLE_OFFICE_INVOICE]
        ROLE_OFFICE_MANAGER:                            [ROLE_OFFICE,ROLE_OFFICE_INVOICE,ROLE_OFFICE_MANAGER,ROLE_OFFICE_STAFF]
        ROLE_OFFICE_ADMIN:                              [ROLE_OFFICE_ADMIN,ROLE_OFFICE_MANAGER]

        # THIS IS PART OF MEDICINE MANAGEMENT

        ROLE_MEDICINE:                                  [ROLE_MEDICINE]
        ROLE_MEDICINE_STAFF:                            [ROLE_MEDICINE,ROLE_MEDICINE_STAFF]
        ROLE_MEDICINE_REPORT:                           [ROLE_MEDICINE,ROLE_MEDICINE_REPORT]
        ROLE_MEDICINE_SALES:                            [ROLE_MEDICINE,ROLE_MEDICINE_SALES]
        ROLE_MEDICINE_PURCHASE:                         [ROLE_MEDICINE,ROLE_MEDICINE_PURCHASE]
        ROLE_MEDICINE_REVERSE_PURCHASE:                 [ROLE_MEDICINE,ROLE_MEDICINE_REVERSE_PURCHASE]
        ROLE_MEDICINE_REVERSE_SALES:                    [ROLE_MEDICINE,ROLE_MEDICINE_REVERSE_SALES]
        ROLE_MEDICINE_STOCK:                            [ROLE_MEDICINE,ROLE_MEDICINE_STOCK,ROLE_MEDICINE_PURCHASE]
        ROLE_MEDICINE_MANAGER:                          [ROLE_MEDICINE,ROLE_MEDICINE_PURCHASE,ROLE_MEDICINE_SALES,ROLE_MEDICINE_STOCK]
        ROLE_MEDICINE_ADMIN:                            [ROLE_MEDICINE_ADMIN,ROLE_MEDICINE,ROLE_MEDICINE_MANAGER,ROLE_MEDICINE_REVERSE]

        # THIS IS PART OF OFFICE MANAGEMENT

        ROLE_DPS:                                       [ROLE_DPS,ROLE_MEDICINE]
        ROLE_DPS_DOCTOR:                                [ROLE_DPS,ROLE_DPS_DOCTOR]
        ROLE_DPS_ADMIN:                                 [ROLE_DPS_DOCTOR,ROLE_DPS,ROLE_DPS_ADMIN]

        # THIS IS PART OF HR and PAYROLL MANAGE

        ROLE_HR:                                        [ROLE_HR]
        ROLE_HR_USER:                                   [ROLE_HR_USER]
        ROLE_HR_EMPLOYEE:                               [ROLE_HR,ROLE_HR_USER,ROLE_HR_EMPLOYEE]
        ROLE_HR_ATTENDANCE:                             [ROLE_HR,ROLE_HR_USER,ROLE_HR_ATTENDANCE]
        ROLE_HR_BRANCH:                                 [ROLE_HR_BRANCH]
        ROLE_PAYROLL:                                   [ROLE_PAYROLL]
        ROLE_PAYROLL_REPORT:                            [ROLE_PAYROLL_REPORT]
        ROLE_PAYROLL_SALARY:                            [ROLE_PAYROLL_SALARY]
        ROLE_PAYROLL_APPROVAL:                          [ROLE_PAYROLL_APPROVAL]
        ROLE_DOMAIN_HR_PAYROLL:                         [ROLE_HR,ROLE_HR_EMPLOYEE,ROLE_HR_USER,ROLE_HR_BRANCH,ROLE_PAYROLL,ROLE_PAYROLL_SALARY,ROLE_PAYROLL_REPORT,ROLE_PAYROLL_APPROVAL,ROLE_HR_ATTENDANCE]

        # THIS IS PART OF INVENTORY

        ROLE_INVENTORY:                                 [ROLE_INVENTORY]
        ROLE_DOMAIN_INVENTORY:                          [ROLE_DOMAIN_INVENTORY]
        ROLE_DOMAIN_INVENTORY_REPORT:                   [ROLE_DOMAIN_INVENTORY_REPORT]
        ROLE_DOMAIN_INVENTORY_STOCK:                    [ROLE_DOMAIN_INVENTORY_STOCK]
        ROLE_DOMAIN_INVENTORY_CONFIG:                   [ROLE_DOMAIN_INVENTORY_CONFIG]
        ROLE_DOMAIN_INVENTORY_PURCHASE:                 [ROLE_DOMAIN_INVENTORY_PURCHASE]
        ROLE_DOMAIN_INVENTORY_CUSTOMER:                 [ROLE_DOMAIN_INVENTORY_CUSTOMER]
        ROLE_DOMAIN_INVENTORY_SALES:                    [ROLE_DOMAIN_INVENTORY_SALES]
        ROLE_DOMAIN_INVENTORY_SALES_POS:                [ROLE_DOMAIN_INVENTORY_SALES_POS]
        ROLE_DOMAIN_INVENTORY_SALES_ONLINE:             [ROLE_DOMAIN_INVENTORY_SALES_ONLINE]
        ROLE_DOMAIN_INVENTORY_SALES_GENERAL:            [ROLE_DOMAIN_INVENTORY_SALES_GENERAL]
        ROLE_DOMAIN_INVENTORY_SALES_MANUAL:             [ROLE_DOMAIN_INVENTORY_SALES_MANUAL]
        ROLE_DOMAIN_INVENTORY_SALES_ORDER:              [ROLE_DOMAIN_INVENTORY_SALES_ORDER]
        ROLE_DOMAIN_INVENTORY_BRANCH:                   [ROLE_DOMAIN_INVENTORY_BRANCH]
        ROLE_DOMAIN_INVENTORY_APPROVAL:                 [ROLE_DOMAIN_INVENTORY_APPROVAL]
        ROLE_DOMAIN_INVENTORY_MANAGER:                  [ROLE_DOMAIN_INVENTORY_MANAGER]
        ROLE_DOMAIN_INVENTORY_DELETE:                   [ROLE_DOMAIN_INVENTORY_DELETE]
        ROLE_DOMAIN_INVENTORY_ADMIN:                    [ROLE_INVENTORY,ROLE_DOMAIN_INVENTORY,ROLE_DOMAIN_INVENTORY_REPORT,ROLE_DOMAIN_INVENTORY_STOCK,ROLE_DOMAIN_INVENTORY_CONFIG,ROLE_DOMAIN_INVENTORY_PURCHASE,ROLE_DOMAIN_INVENTORY_CUSTOMER,ROLE_DOMAIN_INVENTORY_SALES,ROLE_DOMAIN_INVENTORY_APPROVAL,ROLE_DOMAIN_INVENTORY_MANAGER,ROLE_DOMAIN_INVENTORY_BRANCH,ROLE_DOMAIN_INVENTORY_SALES_POS,ROLE_DOMAIN_INVENTORY_SALES_ONLINE,ROLE_DOMAIN_INVENTORY_SALES_MANUAL,ROLE_DOMAIN_INVENTORY_SALES_ORDER,ROLE_APP_SETTING,ROLE_DOMAIN_INVENTORY_ADMIN]

        # THIS IS ECOMMERCE PART

        ROLE_ECOMMERCE:                                 [ROLE_ECOMMERCE]
        ROLE_DOMAIN_ECOMMERCE_PRODUCT:                  [ROLE_DOMAIN_ECOMMERCE_PRODUCT]
        ROLE_DOMAIN_ECOMMERCE_ORDER:                    [ROLE_DOMAIN_ECOMMERCE_ORDER]
        ROLE_DOMAIN_ECOMMERCE_CONFIG:                   [ROLE_DOMAIN_ECOMMERCE_CONFIG,ROLE_APPEARANCE]
        ROLE_DOMAIN_ECOMMERCE:                          [ROLE_ECOMMERCE,ROLE_DOMAIN_ECOMMERCE_PRODUCT,ROLE_DOMAIN_ECOMMERCE_ORDER,ROLE_DOMAIN_ECOMMERCE_CONFIG]

        ROLE_FOOD:                                      [ROLE_FOOD]
        ROLE_DOMAIN_FOOD:                               [ROLE_FOOD,ROLE_DOMAIN_FOOD]
        ROLE_DOMAIN_FOOD_MANAGER:                       [ROLE_DOMAIN_FOOD,ROLE_DOMAIN_FOOD_MANAGER]

        ROLE_GOODS:                                     [ROLE_GOODS]
        ROLE_DOMAIN_GOODS:                              [ROLE_GOODS,ROLE_DOMAIN_GOODS]
        ROLE_DOMAIN_GOODS_MANAGER:                      [ROLE_DOMAIN_GOODS,ROLE_DOMAIN_GOODS_MANAGER]

        ROLE_BUSINESS:                                  [ROLE_BUSINESS]
        ROLE_BUSINESS_INVOICE:                          [ROLE_BUSINESS,ROLE_BUSINESS_INVOICE]
        ROLE_BUSINESS_PURCHASE:                         [ROLE_BUSINESS,ROLE_BUSINESS_PURCHASE]
        ROLE_BUSINESS_STOCK:                            [ROLE_BUSINESS,ROLE_BUSINESS_STOCK]
        ROLE_BUSINESS_PURCHASE_REVERSE:                 [ROLE_BUSINESS,ROLE_BUSINESS_PURCHASE_REVERSE]
        ROLE_BUSINESS_INVOICE_REVERSE:                  [ROLE_BUSINESS,ROLE_BUSINESS_INVOICE_REVERSE]
        ROLE_BUSINESS_MANAGER:                          [ROLE_BUSINESS,ROLE_BUSINESS_INVOICE,ROLE_BUSINESS_PURCHASE,ROLE_BUSINESS_PURCHASE,ROLE_BUSINESS_STOCK,ROLE_BUSINESS_REVERSE_PURCHASE,ROLE_BUSINESS_REVERSE_SALES]

        ROLE_HOTEL:                                     [ROLE_HOTEL]
        ROLE_HOTEL_INVOICE:                             [ROLE_HOTEL,ROLE_HOTEL_INVOICE]
        ROLE_HOTEL_PURCHASE:                            [ROLE_HOTEL,ROLE_HOTEL_PURCHASE]
        ROLE_HOTEL_STOCK:                               [ROLE_HOTEL,ROLE_HOTEL_STOCK]
        ROLE_HOTEL_MANAGER:                             [ROLE_HOTEL,ROLE_HOTEL_MANAGER,ROLE_HOTEL_INVOICE,ROLE_HOTEL_PURCHASE,ROLE_HOTEL_STOCK]

        ROLE_DOMAIN_RESTAURANT:                         [ROLE_RESTAURANT,ROLE_DOMAIN_RESTAURANT]
        ROLE_DOMAIN_RESTAURANT_MANAGER:                 [ROLE_RESTAURANT,ROLE_DOMAIN_RESTAURANT,ROLE_DOMAIN_RESTAURANT_MANAGER]
        ROLE_DOMAIN_RESTAURANT_ADMIN:                   [ROLE_RESTAURANT,ROLE_DOMAIN_RESTAURANT_MANAGER,ROLE_DOMAIN_RESTAURANT_ADMIN]


        ROLE_HOSPITAL:                                  [ROLE_HOSPITAL,ROLE_MEDICINE]
        ROLE_DOMAIN_HOSPITAL_ADMISSION:                 [ROLE_HOSPITAL,ROLE_DOMAIN_HOSPITAL_ADMISSION]
        ROLE_DOMAIN_HOSPITAL_CONFIG:                    [ROLE_HOSPITAL,ROLE_DOMAIN_HOSPITAL_CONFIG]
        ROLE_DOMAIN_HOSPITAL_OPERATOR:                  [ROLE_HOSPITAL,ROLE_DOMAIN_HOSPITAL_OPERATOR]
        ROLE_DOMAIN_HOSPITAL_LAB:                       [ROLE_HOSPITAL,ROLE_DOMAIN_HOSPITAL_LAB]
        ROLE_DOMAIN_HOSPITAL_DOCTOR:                    [ROLE_HOSPITAL,ROLE_DOMAIN_HOSPITAL_DOCTOR]
        ROLE_DOMAIN_HOSPITAL_MANAGER:                   [ROLE_HOSPITAL,ROLE_DOMAIN_HOSPITAL_DOCTOR,ROLE_DOMAIN_HOSPITAL_OPERATOR,ROLE_DOMAIN_HOSPITAL_ADMISSION]
        ROLE_DOMAIN_HOSPITAL_ADMIN:                     [ROLE_DOMAIN_HOSPITAL_MANAGER,ROLE_DOMAIN_HOSPITAL_ADMIN,ROLE_DOMAIN_HOSPITAL_LAB,ROLE_DOMAIN_HOSPITAL_CONFIG,ROLE_DOMAIN_HOSPITAL_ADMISSION]


        ROLE_DOMAIN_DMS_LAB:                            [ROLE_DMS,ROLE_DOMAIN_DMS_LAB]
        ROLE_DOMAIN_DMS_DOCTOR:                         [ROLE_DMS,ROLE_DOMAIN_DMS_DOCTOR]
        ROLE_DOMAIN_DMS_MANAGER:                        [ROLE_DMS,ROLE_DOMAIN_DMS_MANAGER,ROLE_DOMAIN_DMS_DOCTOR,ROLE_DOMAIN_DMS_OPERATOR]
        ROLE_DOMAIN_DMS_ADMIN:                          [ROLE_DOMAIN_DMS_MANAGER,ROLE_DOMAIN_DMS_ADMIN,ROLE_DOMAIN_DMS_CONFIG,ROLE_DOMAIN_DMS_OPERATOR,ROLE_DOMAIN_DMS_LAB,ROLE_DOMAIN_DMS_DOCTOR]


        ROLE_DOMAIN_PURCHASE:                           [ROLE_DOMAIN_PURCHASE]
        ROLE_APP_SETTING:                               [ROLE_APP_SETTING]
  

        ROLE_SMS:                                       [ROLE_SMS]
        ROLE_SMS_MANAGER:                               [ROLE_SMS,ROLE_SMS_MANAGER]
        ROLE_SMS_CONFIG:                                [ROLE_SMS,ROLE_SMS_CONFIG]
        ROLE_SMS_BULK:                                  [ROLE_SMS,ROLE_SMS_BULK]
        ROLE_SMS_ADMIN:                                 [ROLE_SMS,ROLE_SMS_BULK,ROLE_SMS_CONFIG,ROLE_SMS_MANAGER]


        # THIS IS PART OF MAIN DOMAIN MANAGE

        ROLE_DOMAIN_MANAGER:                            []
        ROLE_DOMAIN:                                    [ROLE_DOMAIN,ROLE_AGENT,ROLE_RESTAURANT,ROLE_BUSINESS,ROLE_HOSPITAL,ROLE_GOODS,ROLE_DOMAIN_WEBSITE,ROLE_DOMAIN_INVENTORY_ADMIN,ROLE_DOMAIN_HR_PAYROLL,ROLE_DOMAIN_ACCOUNTING,ROLE_DOMAIN_ECOMMERCE,ROLE_APP_SETTING,ROLE_APPEARANCE,ROLE_DOMAIN_HOSPITAL_ADMIN,ROLE_DOMAIN_DMS_ADMIN,ROLE_DOMAIN_ADMIN,ROLE_DOMAIN_RESTAURANT_ADMIN,ROLE_SMS,ROLE_SMS_ADMIN,ROLE_ACCOUNTING,ROLE_OFFICE_ADMIN,ROLE_OFFICE,ROLE_DPS,ROLE_MEDICINE,ROLE_MEDICINE_ADMIN,ROLE_BUSINESS_MANAGER,ROLE_HOTEL,ROLE_ELECTION]

        ROLE_ADMIN_OPERATION_USER:                      [ROLE_ADMIN_OPERATION_USER,ROLE_DOMAIN]
        ROLE_ADMIN_OPERATION_MANAGER:                   [ROLE_ADMIN_OPERATION_MANAGER,ROLE_ADMIN_OPERATION_USER]
        ROLE_ADMIN_OPERATION_APPROVE:                   [ROLE_ADMIN_OPERATION_APPROVE,ROLE_ADMIN_OPERATION_MANAGER]
        ROLE_ADMIN:                                     [ROLE_ADMIN,ROLE_DOMAIN,ROLE_ADMIN_OPERATION_APPROVE]
        ROLE_SUPER_ADMIN:                               [ROLE_SUPER_ADMIN,ROLE_ADMIN,ROLE_DOMAIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            ajax_form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: landing_page
                always_use_default_target_path: true
            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 31536000 # 1 week in seconds
                path:     /home

    access_control:
        - { path: ^/login$,             role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,              role: ROLE_ADMIN }
        - { path: ^/admin,              role: ROLE_SUPER_ADMIN }
        - { path: ^/domain,             role: ROLE_DOMAIN }
        - { path: ^/website,            role: ROLE_WEBSITE }
        - { path: ^/appearance/,        role: ROLE_APPEARANCE }
        - { path: ^/finance,            role: ROLE_ACCOUNTING }
        - { path: ^/hr/employee,        role: ROLE_USER }
        - { path: ^/hr,                 role: ROLE_HR }
        - { path: ^/office,             role: ROLE_OFFICE }
        - { path: ^/human-resource,     role: ROLE_HR }
        - { path: ^/payroll,            role: ROLE_PAYROLL }
        - { path: ^/inventory,          role: ROLE_INVENTORY }
        - { path: ^/hms,                role: ROLE_HOSPITAL }
        - { path: ^/restaurant,         role: ROLE_RESTAURANT }
        - { path: ^/election,           role: ROLE_ELECTION }
        - { path: ^/dms,                role: ROLE_DMS }
        - { path: ^/doctor-prescription,role: ROLE_DPS }
        - { path: ^/medicine,           role: ROLE_MEDICINE }
        - { path: ^/vendor,             role: ROLE_DOMAIN }
        - { path: ^/web-builder/build,  role: ROLE_DOMAIN }
        - { path: ^/customer,           role: ROLE_CUSTOMER }
        - { path: ^/agent,              role: ROLE_AGENT }
        - { path: ^/sms,                role: ROLE_SMS }
        - { path: ^/user,               role: ROLE_USER }
        - { path: ^/general,            role: ROLE_USER }
        - { path: ^/e-commerce,         role: ROLE_ECOMMERCE }
        - { path: ^/food,               role: ROLE_FOOD }
        - { path: ^/goods,              role: ROLE_GOODS }
        - { path: ^/business,           role: ROLE_BUSINESS }
        - { path: ^/appsetting,         role: ROLE_APP_SETTING }
        - { path: ^/,                   role: IS_AUTHENTICATED_ANONYMOUSLY }
