security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:

        ROLE_CUSTOMER:                                  [ROLE_USER]
        ROLE_VENDOR:                                    [ROLE_USER]
        ROLE_MANAGER:                                   [ROLE_USER]
        ROLE_ADMIN_OPERATION_USER:                      [ROLE_USER]
        ROLE_ADMIN_OPERATION_MANAGER:                   [ROLE_USER]
        ROLE_DOMAIN_CUSTOMER:                           [ROLE_USER]
        ROLE_DOMAIN_USER:                               [ROLE_USER]

        # THIS IS PART OF WEBSITE MANAGE

        ROLE_WEBSITE:                                   [ROLE_WEBSITE]
        ROLE_DOMAIN_WEBSITE_CUSTOMER:                   [ROLE_DOMAIN_WEBSITE_CUSTOMER]
        ROLE_DOMAIN_WEBSITE_MANAGER:                    [ROLE_DOMAIN_WEBSITE_MANAGER]
        ROLE_DOMAIN_WEBSITE_SETTING:                    [ROLE_DOMAIN_WEBSITE_SETTING]
        ROLE_DOMAIN_WEBSITE:                            [ROLE_WEBSITE,ROLE_DOMAIN_WEBSITE_CUSTOMER,ROLE_DOMAIN_WEBSITE_SETTING,ROLE_DOMAIN_WEBSITE_MANAGER]

        # THIS IS PART OF ACCOUNTING MANAGE

        ROLE_ACCOUNTING:                                [ROLE_ACCOUNTING]
        ROLE_DOMAIN_ACCOUNTING_REPORT:                  [ROLE_DOMAIN_ACCOUNTING_REPORT]
        ROLE_DOMAIN_ACCOUNTING_TRANSACTION:             [ROLE_DOMAIN_ACCOUNTING_TRANSACTION]
        ROLE_DOMAIN_ACCOUNTING_EXPENDITURE:             [ROLE_DOMAIN_ACCOUNTING_EXPENDITURE]
        ROLE_DOMAIN_ACCOUNTING_PURCHASE:                [ROLE_DOMAIN_ACCOUNTING_PURCHASE]
        ROLE_DOMAIN_ACCOUNTING_SALES:                   [ROLE_DOMAIN_ACCOUNTING_SALES]
        ROLE_DOMAIN_ACCOUNTING_ECOMMERCE:               [ROLE_DOMAIN_ACCOUNTING_ECOMMERCE]
        ROLE_DOMAIN_ACCOUNTING_BANK:                    [ROLE_DOMAIN_ACCOUNTING_BANK]
        ROLE_DOMAIN_ACCOUNTING_PETTY_CASH:              [ROLE_DOMAIN_ACCOUNTING_PETTY_CASH]
        ROLE_DOMAIN_ACCOUNTING_JOURNAL:                 [ROLE_DOMAIN_ACCOUNTING_JOURNAL]
        ROLE_DOMAIN_ACCOUNTING_APPROVAL:                [ROLE_DOMAIN_ACCOUNTING_APPROVAL]
        ROLE_DOMAIN_ACCOUNTING_CONFIG:                  [ROLE_DOMAIN_ACCOUNTING_CONFIG]
        ROLE_DOMAIN_ACCOUNTING:                         [ROLE_ACCOUNTING,ROLE_DOMAIN_ACCOUNTING_REPORT,ROLE_DOMAIN_ACCOUNTING_JOURNAL,ROLE_DOMAIN_ACCOUNTING_PETTY_CASH,ROLE_DOMAIN_ACCOUNTING_BANK,ROLE_DOMAIN_ACCOUNTING_SALES,ROLE_DOMAIN_ACCOUNTING_TRANSACTION,ROLE_DOMAIN_ACCOUNTING_EXPENDITURE,ROLE_DOMAIN_ACCOUNTING_PURCHASE,ROLE_DOMAIN_ACCOUNTING_APPROVAL,ROLE_DOMAIN_ACCOUNTING_CONFIG]


        # THIS IS PART OF HR and PAYROLL MANAGE

        ROLE_HR:                                        [ROLE_HR]
        ROLE_HR_USER:                                   [ROLE_HR_USER]
        ROLE_HR_BRANCH:                                 [ROLE_HR_BRANCH]
        ROLE_PAYROLL:                                   [ROLE_PAYROLL]
        ROLE_PAYROLL_REPORT:                            [ROLE_PAYROLL_REPORT]
        ROLE_PAYROLL_SALARY:                            [ROLE_PAYROLL_SALARY]
        ROLE_PAYROLL_APPROVAL:                          [ROLE_PAYROLL_APPROVAL]
        ROLE_DOMAIN_HR_PAYROLL:                         [ROLE_HR,ROLE_HR_USER,ROLE_HR_BRANCH,ROLE_PAYROLL,ROLE_PAYROLL_SALARY,ROLE_PAYROLL_REPORT,ROLE_PAYROLL_APPROVAL]


        # THIS IS PART OF INVENTORY

        ROLE_INVENTORY:                                 [ROLE_INVENTORY]
        ROLE_DOMAIN_INVENTORY_REPORT:                   [ROLE_DOMAIN_INVENTORY_REPORT]
        ROLE_DOMAIN_INVENTORY_STOCK:                    [ROLE_DOMAIN_INVENTORY_STOCK]
        ROLE_DOMAIN_INVENTORY_CONFIG:                   [ROLE_DOMAIN_INVENTORY_CONFIG]
        ROLE_DOMAIN_INVENTORY_PURCHASE:                 [ROLE_DOMAIN_INVENTORY_PURCHASE]
        ROLE_DOMAIN_INVENTORY_CUSTOMER:                 [ROLE_DOMAIN_INVENTORY_CUSTOMER]
        ROLE_DOMAIN_INVENTORY_SALES:                    [ROLE_DOMAIN_INVENTORY_SALES]
        ROLE_DOMAIN_INVENTORY_APPROVAL:                 [ROLE_DOMAIN_INVENTORY_APPROVAL]
        ROLE_DOMAIN_INVENTORY:                          [ROLE_INVENTORY,ROLE_INVENTORY_REPORT,ROLE_DOMAIN_INVENTORY_STOCK,ROLE_DOMAIN_INVENTORY_CONFIG,ROLE_DOMAIN_INVENTORY_PURCHASE,ROLE_DOMAIN_INVENTORY_CUSTOMER,ROLE_DOMAIN_INVENTORY_SALES,ROLE_DOMAIN_INVENTORY_APPROVAL]

        # THIS IS ECOMMERCE PART

        ROLE_ECOMMERCE:                                 [ROLE_ECOMMERCE]
        ROLE_DOMAIN_ECOMMERCE_PRODUCT:                  [ROLE_DOMAIN_ECOMMERCE_PRODUCT]
        ROLE_DOMAIN_ECOMMERCE_ORDER:                    [ROLE_DOMAIN_ECOMMERCE_ORDER]
        ROLE_DOMAIN_ECOMMERCE_SETTING:                  [ROLE_DOMAIN_ECOMMERCE_SETTING]
        ROLE_DOMAIN_ECOMMERCE:                          [ROLE_ECOMMERCE,ROLE_DOMAIN_ECOMMERCE_PRODUCT,ROLE_DOMAIN_ECOMMERCE_ORDER,ROLE_DOMAIN_ECOMMERCE_SETTING]



        ROLE_FOOD:                                      [ROLE_FOOD]
        ROLE_DOMAIN_FOOD:                               [ROLE_FOOD,ROLE_DOMAIN_FOOD]
        ROLE_DOMAIN_FOOD_MANAGER:                       [ROLE_DOMAIN_FOOD,ROLE_DOMAIN_FOOD_MANAGER]

        ROLE_GOODS:                                     [ROLE_GOODS]
        ROLE_DOMAIN_GOODS:                              [ROLE_GOODS,ROLE_DOMAIN_GOODS]
        ROLE_DOMAIN_GOODS_MANAGER:                      [ROLE_DOMAIN_GOODS,ROLE_DOMAIN_GOODS_MANAGER]

        ROLE_SERVICE:                                   [ROLE_SERVICE]
        ROLE_DOMAIN_SERVICE:                            [ROLE_SERVICE,ROLE_DOMAIN_SERVICE]
        ROLE_DOMAIN_SERVICE_MANAGER:                    [ROLE_DOMAIN_SERVICE,ROLE_DOMAIN_SERVICE_MANAGER]


        ROLE_DOMAIN_PURCHASE:                           [ROLE_DOMAIN_PURCHASE]
        ROLE_APP_SETTING:                               [ROLE_APP_SETTING]


        # THIS IS PART OF MAIN DOMAIN MANAGE

        ROLE_DOMAIN_MANAGER:                        []
        ROLE_DOMAIN:                                [ROLE_DOMAIN,ROLE_DOMAIN_WEBSITE,ROLE_DOMAIN_INVENTORY,ROLE_DOMAIN_HR_PAYROLL,ROLE_DOMAIN_ACCOUNTING,ROLE_DOMAIN_ECOMMERCE]

        ROLE_ADMIN_OPERATION_USER:                  [ROLE_ADMIN_OPERATION_USER,ROLE_DOMAIN]
        ROLE_ADMIN_OPERATION_MANAGER:               [ROLE_ADMIN_OPERATION_MANAGER,ROLE_ADMIN_OPERATION_USER]
        ROLE_ADMIN_OPERATION_APPROVE:               [ROLE_ADMIN_OPERATION_APPROVE,ROLE_ADMIN_OPERATION_MANAGER]
        ROLE_ADMIN:                                 [ROLE_ADMIN,ROLE_DOMAIN,ROLE_ADMIN_OPERATION_APPROVE]
        ROLE_SUPER_ADMIN:                           [ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            ajax_form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: landing_page
                always_use_default_target_path: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$,             role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,              role: ROLE_SUPER_ADMIN }
        - { path: ^/domain,             role: ROLE_DOMAIN }
        - { path: ^/website,            role: ROLE_WEBSITE }
        - { path: ^/finance,            role: ROLE_ACCOUNTING }
        - { path: ^/hr,                 role: ROLE_HR }
        - { path: ^/payroll,            role: ROLE_PAYROLL }
        - { path: ^/inventory,          role: ROLE_INVENTORY }
        - { path: ^/vendor,             role: ROLE_DOMAIN }
        - { path: ^/web-builder/build,  role: ROLE_DOMAIN }
        - { path: ^/customer,           role: ROLE_CUSTOMER }
        - { path: ^/user,               role: ROLE_USER }
        - { path: ^/general,            role: ROLE_USER }
        - { path: ^/ecommerce,          role: ROLE_ECOMMERCE }
        - { path: ^/food,               role: ROLE_FOOD }
        - { path: ^/goods,              role: ROLE_GOODS }
        - { path: ^/service,            role: ROLE_SERVICE }
        - { path: ^/appsetting,         role: ROLE_APP_SETTING }
        - { path: ^/,                   role: IS_AUTHENTICATED_ANONYMOUSLY }
