hospital_purchase:
    resource: "@HospitalBundle/Resources/config/routing/purchase.yml"
    prefix:   /purchase

hospital_vendor:
    resource: "@HospitalBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor

hospital_invoice:
    resource: "@HospitalBundle/Resources/config/routing/invoice.yml"
    prefix:   /invoice

hospital_doctor_invoice:
    resource: "@HospitalBundle/Resources/config/routing/doctorinvoice.yml"
    prefix:   /doctor-invoice

hospital_invoice_admission:
    resource: "@HospitalBundle/Resources/config/routing/invoiceadmission.yml"
    prefix:   /invoice-admission

hospital_invoice_particular:
    resource: "@HospitalBundle/Resources/config/routing/invoiceparticular.yml"
    prefix:   /invoice-particular

hospital_particular:
    resource: "@HospitalBundle/Resources/config/routing/particular.yml"
    prefix:   /particular

hospital_pathology:
    resource: "@HospitalBundle/Resources/config/routing/pathology.yml"
    prefix:   /pathology

hospital_pathologicalreport:
    resource: "@HospitalBundle/Resources/config/routing/pathologicalreport.yml"
    prefix:    /pathological-report

hospital_doctor:
    resource: "@HospitalBundle/Resources/config/routing/doctor.yml"
    prefix:   /doctor

hospital_cabin:
    resource: "@HospitalBundle/Resources/config/routing/cabin.yml"
    prefix:   /cabin-ward

hospital_surgery:
    resource: "@HospitalBundle/Resources/config/routing/surgery.yml"
    prefix:   /surgery-operation

hospital_medicine:
    resource: "@HospitalBundle/Resources/config/routing/medicine.yml"
    prefix:   /medicine

hospital_referred_doctor:
    resource: "@HospitalBundle/Resources/config/routing/referreddoctor.yml"
    prefix:   /referred-doctor

hospital_category:
    resource: "@HospitalBundle/Resources/config/routing/category.yml"
    prefix:   /category

hospital_config:
    resource: "@HospitalBundle/Resources/config/routing/config.yml"
    prefix:   /config

hospital_homepage:
    path:     /
    defaults: { _controller: HospitalBundle:Default:index }
