hms_invoice_temporary_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:new" }
    options:
            expose: true

hms_invoice_temporary_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:create" }
    methods:  POST


hms_invoice_temporary_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:particularSearch" }


hms_invoice_temporary_particular_add:
    path:     /particular-add
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:addParticular" }
    methods:  POST
    options:
            expose: true


hms_invoice_temporary_discount_update:
    path:     /invoice/invoice-dicount-update
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

hms_invoice_temporary_discount_delete:
    path:     /{id}/discount-delete
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:discountDelete" }

hms_invoice_temporary_particular_delete:
    path:     /{id}/particular-delete
    defaults: { _controller: "HospitalBundle:Invoice:invoiceParticularDelete" }

