tally_assetsissue:
    path:     /
    defaults: { _controller: "TallyBundle:AssetsIssue:index" }


tally_assetsissue_show:
    path:     /{id}/show
    defaults: { _controller: "TallyBundle:AssetsIssue:show" }


tally_assetsissue_new:
    path:     /new
    defaults: { _controller: "TallyBundle:AssetsIssue:new" }

tally_assetsissue_edit:
    path:     /{code}/assets-issue-item
    defaults: { _controller: "TallyBundle:AssetsIssue:edit" }


tally_assetsissue_empty_delete:
    path:     /empty-delete
    defaults: { _controller: "TallyBundle:AssetsIssue:edit" }


tally_assetsissue_approve:
    path:     /{id}/{process}/approve
    defaults: { _controller: "TallyBundle:AssetsIssue:approve" }
    options:
           expose: true

tally_assetsissue_update:
    path:     /{id}/update
    defaults: { _controller: "TallyBundle:AssetsIssue:update" }
    methods:  [POST, PUT]

tally_assetsissue_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "TallyBundle:AssetsIssue:invoicePrint" }
