tally_issue:
    path:     /
    defaults: { _controller: "TallyBundle:Issue:index" }

tally_issue_new:
    path:     /new
    defaults: { _controller: "TallyBundle:Issue:new" }

tally_issue_edit:
    path:     /{code}/online
    defaults: { _controller: "TallyBundle:Issue:edit" }

tally_issue_update:
    path:     /{id}/update
    defaults: { _controller: "TallyBundle:Issue:update" }
    methods:  [POST, PUT]

tally_issue_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "TallyBundle:Issue:invoicePrint" }

tally_issue_sales_reverse:
    path:     /{invoice}/invoice-reverse
    defaults: { _controller: "TallyBundle:Issue:reverse" }

tally_issue_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "TallyBundle:Issue:deleteEmptyInvoice" }