tallyitem:
    path:     /
    defaults: { _controller: "TallyBundle:Item:index" }

tallyitem_show:
    path:     /{id}/show
    defaults: { _controller: "TallyBundle:Item:show" }

tallyitem_new:
    path:     /new
    defaults: { _controller: "TallyBundle:Item:new" }

tallyitem_create:
    path:     /create
    defaults: { _controller: "TallyBundle:Item:create" }
    methods:  POST

tallyitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "TallyBundle:Item:edit" }

tallyitem_inline_modify:
    path:     /item-inline-update
    defaults: { _controller: "TallyBundle:Item:updateSalesPrice" }
    methods:  POST
    options:
            expose: true

tallyitem_gallery:
    path:     /{item}/upload
    defaults: { _controller: "TallyBundle:Item:uploadItemImage" }
    options:
           expose: true

tallyitem_status:
    path:     /{id}/status
    defaults: { _controller: "TallyBundle:Item:status" }

tallyitem_is_web:
    path:     /{id}/is-web
    defaults: { _controller: "TallyBundle:Item:isWeb" }

tallyitem_update:
    path:     /{id}/update
    defaults: { _controller: "TallyBundle:Item:update" }
    methods:  [POST, PUT]

tallyitem_edit_web:
    path:     /{id}/edit-assets
    defaults: { _controller: "TallyBundle:Item:editAssets" }

tallyitem_web_status:
    path:     /{id}/item-web-status
    defaults: { _controller: "TallyBundle:Item:webStatus" }


tallyitem_web_update:
    path:     /{id}/web-update
    defaults: { _controller: "TallyBundle:Item:updateAssets" }
    methods:  [POST, PUT]

tallyitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "TallyBundle:Item:delete" }

tallyitem_search:
    path:     /search
    defaults: { _controller: "TallyBundle:Item:autoSearch" }
    options:
           expose: true

tallyitem_search_all:
    path:     /all-search
    defaults: { _controller: "TallyBundle:Item:autoSearchItemAll" }
    options:
           expose: true

assets_tallyitem_inline_update:
    path:     /{vendor}/vendor-item
    defaults: { _controller: "TallyBundle:Item:vendorItem" }
    options:
           expose: true

tallyitem_price:
    path:      /price
    defaults: { _controller: "TallyBundle:Item:price" }
    methods:  [POST]

tallyitem_inline_discount_search:
    path:     /inline-discount-search
    defaults: { _controller: "TallyBundle:Item:discountSelect" }
    options:
           expose: true

tallyitem_inline_tag_search:
    path:     /inline-tag-search
    defaults: { _controller: "TallyBundle:Item:tagSelect" }
    options:
           expose: true

tallyitem_inline_update:
    path:     /inline-item-update
    defaults: { _controller: "TallyBundle:Item:inlineItemUpdate" }
    methods:  POST
    options:
            expose: true

