tallybrand:
    path:     /
    defaults: { _controller: "TallyBundle:Brand:index" }

tallybrand_search:
    path:     /search
    defaults: { _controller: "TallyBundle:Brand:autoSearch" }
    options:
            expose: true

tallybrand_name:
    path:      /{brand}/brand-name
    defaults: { _controller: "TallyBundle:Brand:searchBrandName" }
    options:
            expose: true

tallybrand_show:
    path:     /{id}/show
    defaults: { _controller: "TallyBundle:Brand:show" }

tallybrand_new:
    path:     /new
    defaults: { _controller: "TallyBundle:Brand:new" }

tallybrand_create:
    path:     /create
    defaults: { _controller: "TallyBundle:Brand:create" }
    methods:  POST

tallybrand_edit:
    path:     /{id}/edit
    defaults: { _controller: "TallyBundle:Brand:edit" }

tallybrand_update:
    path:     /{id}/update
    defaults: { _controller: "TallyBundle:Brand:update" }
    methods:  [POST, PUT]

tallybrand_delete:
    path:     /{id}/delete
    defaults: { _controller: "TallyBundle:Brand:delete" }
