tally_itemissue:
    path:     /
    defaults: { _controller: "TallyBundle:Issue:index" }


tally_itemissue_show:
    path:     /{id}/show
    defaults: { _controller: "TallyBundle:Issue:show" }

tally_itemissue_show_preview:
    path:     /{id}/show-preview
    defaults: { _controller: "TallyBundle:Issue:showPreview" }
    methods:  GET
    options:
            expose: true

tally_itemissue_new:
    path:     /new
    defaults: { _controller: "TallyBundle:Issue:new" }

tally_itemissue_edit:
    path:     /{code}/item-delivery-issue
    defaults: { _controller: "TallyBundle:Issue:edit" }


tally_itemissue_approve:
    path:     /{id}/{process}/approve
    defaults: { _controller: "TallyBundle:Issue:approve" }
    options:
           expose: true

tally_itemissue_update:
    path:     /{id}/update
    defaults: { _controller: "TallyBundle:Issue:update" }
    methods:  [POST, PUT]

tally_itemissue_item:
    path:     /issue-item-details
    defaults: { _controller: "TallyBundle:Issue:salesItem" }

tally_itemissue_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "TallyBundle:Issue:invoicePrint" }

tally_itemissue_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "TallyBundle:Issue:deleteEmptyInvoice" }