assetsitembrand:
    path:     /
    defaults: { _controller: "TallyBundle:ItemBrand:index" }

assetsitembrand_search:
    path:     /search
    defaults: { _controller: "TallyBundle:ItemBrand:autoSearch" }
    options:
            expose: true

assetsitembrand_name:
    path:      /{brand}/brand-name
    defaults: { _controller: "TallyBundle:ItemBrand:searchItemBrandName" }
    options:
            expose: true

assetsitembrand_show:
    path:     /{id}/show
    defaults: { _controller: "TallyBundle:ItemBrand:show" }

assetsitembrand_new:
    path:     /new
    defaults: { _controller: "TallyBundle:ItemBrand:new" }

assetsitembrand_create:
    path:     /create
    defaults: { _controller: "TallyBundle:ItemBrand:create" }
    methods:  POST

assetsitembrand_edit:
    path:     /{id}/edit
    defaults: { _controller: "TallyBundle:ItemBrand:edit" }

assetsitembrand_update:
    path:     /{id}/update
    defaults: { _controller: "TallyBundle:ItemBrand:update" }
    methods:  [POST, PUT]

assetsitembrand_delete:
    path:     /{id}/delete
    defaults: { _controller: "TallyBundle:ItemBrand:delete" }
