tally_purchase:
    path:     /
    defaults: { _controller: "TallyBundle:Purchase:index" }

tally_purchase_new:
    path:     /new
    defaults: { _controller: "TallyBundle:Purchase:new" }

tally_purchase_edit:
    path:     /{id}/edit
    defaults: { _controller: "TallyBundle:Purchase:edit" }

tally_purchase_show:
    path:     /{id}/show
    defaults: { _controller: "TallyBundle:Purchase:show" }

tally_purchase_update:
    path:     /{id}/update
    defaults: { _controller: "TallyBundle:Purchase:update" }
    methods:  [POST, PUT]

tally_purchase_particular_add:
    path:     /{id}/particular-add
    defaults: { _controller: "TallyBundle:Purchase:addParticular" }
    methods:  POST
    options:
            expose: true

tally_purchase_status:
    path:     /{id}/status
    defaults: { _controller: "TallyBundle:Purchase:status" }

tally_purchase_delete:
    path:     /{id}/delete
    defaults: { _controller: "TallyBundle:Purchase:delete" }


tally_purchase_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "TallyBundle:Purchase:approved" }

tally_purchase_particular_delete:
    path:     /{invoice}/{id}/item-delete
    defaults: { _controller: "TallyBundle:Purchase:invoiceParticularDelete" }

tally_purchase_discount_update:
    path:     /dicount-update
    defaults: { _controller: "TallyBundle:Purchase:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

