tally_customer_update:
    path:     /customer-create-update
    defaults: { _controller: "TallyBundle:Sales:customerUpdate" }
    methods:  [POST, PUT]
    options:
            expose: true

tally_customer_location_search:
    path:     /customer-location-search
    defaults: { _controller: "TallyBundle:Sales:locationSearch" }
    options:
            expose: true


tally_branch_stock_item:
    path:     /{item}/branch-stock-item-details
    defaults: { _controller: "TallyBundle:Sales:branchStockItemDetails" }
    methods:  GET
    options:
            expose: true

tally_sales_print:
    path:     /{code}/print
    defaults: { _controller: "TallyBundle:Sales:print" }

tally_sales_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "TallyBundle:Sales:invoicePrint" }

tally_sales_print_chalan:
    path:     /{invoice}/chalan
    defaults: { _controller: "TallyBundle:Sales:chalanPrint" }

tally_sales_discount_update:
    path:     /sales/discount-update
    defaults: { _controller: "TallyBundle:Sales:salesDiscountUpdate" }
    methods:  POST
    options:
            expose: true

tally_stcok_barcode_autocomplete_search:
    path:     /barcode-item-search
    defaults: { _controller: "TallyBundle:StockItem:searchAutoComplete" }
    options:
            expose: true

tally_stcok_item_autocomplete_search:
    path:     /item-search
    defaults: { _controller: "TallyBundle:StockItem:itemAutoSearch" }
    options:
            expose: true


tally_sales_item_purchase:
    path:     /item-purchase-details
    defaults: { _controller: "TallyBundle:StockItem:itemPurchaseDetails" }
    methods:  POST
    options:
            expose: true

tally_sales_barcode_item_add:
    path:     /add-stock-barcode-item
    defaults: { _controller: "TallyBundle:Sales:barcodeSearch" }
    options:
           expose: true


tally_sales_sales_item_insert:
    path:     /insert-sales-barcode-item
    defaults: { _controller: "TallyBundle:Sales:salesItemSave" }
    methods:  POST
    options:
            expose: true

tally_sales_sales_item_update:
    path:     /update-sales-barcode-item
    defaults: { _controller: "TallyBundle:Sales:salesItemUpdate" }
    methods:  POST
    options:
            expose: true

tally_salesitem_delete:
    path:     /{sales}/{salesItem}/delete
    defaults: { _controller: "TallyBundle:Sales:itemDelete" }

tally_sales_item_serial_update:
    path:     /{salesItem}/update-serial-no
    defaults: { _controller: "TallyBundle:Sales:itemSerialNoUpdate" }

tally_sales_inline_update:
    path:     /sales/inline-update
    defaults: { _controller: "TallyBundle:Sales:salesInlineUpdate" }
    methods:  POST
    options:
            expose: true

tally_sales_inline_process_update:
    path:     /sales/inline-process-update
    defaults: { _controller: "TallyBundle:Sales:salesInlineProcessUpdate" }
    methods:  POST
    options:
            expose: true

tally_sales_inline_status_select:
    path:     /inline-status-select
    defaults: { _controller: "TallyBundle:Sales:salesSelect" }
    options:
           expose: true


tally_sales_invoice_search:
    path:     /sales-invoice-sesrch
    defaults: { _controller: "TallyBundle:Sales:salesInvoiceSearch" }
    options:
           expose: true

tally_sales_invoice_name:
    path:      /{invoice}/sales-invoice
    defaults: { _controller: "TallyBundle:Sales:searchSalesInvoiceName" }
    options:
            expose: true