tally_sales:
    path:     /
    defaults: { _controller: "TallyBundle:Sales:index" }

tally_sales_item:
    path:     /sales-item
    defaults: { _controller: "TallyBundle:Sales:salesItem" }

tally_sales_item_search:
    path:     /search
    defaults: { _controller: "TallyBundle:Sales:search" }
    methods:  POST
    options:
            expose: true

tally_sales_online_item_search:
    path:     /search
    defaults: { _controller: "TallyBundle:SalesOnline:search" }
    methods:  POST
    options:
            expose: true


tally_sales_item_purchase:
    path:     /item-purchase-details
    defaults: { _controller: "TallyBundle:Sales:itemPurchaseDetails" }
    methods:  POST
    options:
            expose: true

tally_branch_stock_item:
    path:     /{item}/branch-stock-item-details
    defaults: { _controller: "TallyBundle:Sales:branchStockItemDetails" }
    methods:  GET
    options:
            expose: true

tally_sales_show:
    path:     /{id}/show
    defaults: { _controller: "TallyBundle:Sales:show" }

tally_sales_new:
    path:     /new
    defaults: { _controller: "TallyBundle:Sales:new" }

tally_sales_create:
    path:     /create
    defaults: { _controller: "TallyBundle:Sales:new" }


tally_sales_edit:
    path:     /{code}/pos
    defaults: { _controller: "TallyBundle:Sales:edit" }

tally_sales_print:
    path:     /{code}/print
    defaults: { _controller: "TallyBundle:Sales:print" }

tally_sales_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "TallyBundle:Sales:invoicePrint" }

tally_sales_print_chalan:
    path:     /{invoice}/chalan
    defaults: { _controller: "TallyBundle:Sales:chalanPrint" }

tally_sales_discount_update:
    path:     /sales/discount-update
    defaults: { _controller: "TallyBundle:Sales:salesDiscountUpdate" }
    methods:  POST
    options:
            expose: true

tally_sales_item_update:
    path:     /sales/item/update
    defaults: { _controller: "TallyBundle:Sales:salesItemUpdate" }
    methods:  POST
    options:
            expose: true

tally_sales_approve:
    path:     /{id}/approve
    defaults: { _controller: "TallyBundle:Sales:approve" }
    options:
           expose: true

tally_sales_update:
    path:     /{id}/update
    defaults: { _controller: "TallyBundle:Sales:update" }
    methods:  [POST, PUT]

tally_sales_reset:
    path:     /{id}/reset
    defaults: { _controller: "TallyBundle:Sales:reset" }

tally_sales_delete:
    path:     /{id}/delete
    defaults: { _controller: "TallyBundle:Sales:delete" }

tally_sales_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "TallyBundle:Sales:deleteEmptyInvoice" }

tally_salesitem_delete:
    path:     /{sales}/{salesItem}/delete
    defaults: { _controller: "TallyBundle:Sales:itemDelete" }

tally_sales_item_serial_update:
    path:     /{salesItem}/update-serial-no
    defaults: { _controller: "TallyBundle:Sales:itemSerialNoUpdate" }

tally_sales_inline_update:
    path:     /sales/inline-update
    defaults: { _controller: "TallyBundle:Sales:salesInlineUpdate" }
    methods:  POST
    options:
            expose: true

tally_sales_inline_process_update:
    path:     /sales/inline-process-update
    defaults: { _controller: "TallyBundle:Sales:salesInlineProcessUpdate" }
    methods:  POST
    options:
            expose: true

tally_sales_inline_status_select:
    path:     /inline-status-select
    defaults: { _controller: "TallyBundle:Sales:salesSelect" }
    options:
           expose: true

tally_sales_mobile_update:
    path:     /sales/mobile-update
    defaults: { _controller: "TallyBundle:Sales:salesInlineMobileUpdate" }
    methods:  POST
    options:
            expose: true

tally_sales_invoice_search:
    path:     /sales-invoice-sesrch
    defaults: { _controller: "TallyBundle:Sales:salesInvoiceSearch" }
    options:
           expose: true

tally_sales_invoice_name:
    path:      /{invoice}/sales-invoice
    defaults: { _controller: "TallyBundle:Sales:searchSalesInvoiceName" }
    options:
            expose: true