tally_stockitem:
    path:     /
    defaults: { _controller: "TallyBundle:StockItem:index" }
    options:
        expose: true

tally_stockitem_show:
    path:     /{item}/show
    defaults: { _controller: "TallyBundle:StockItem:show" }

tally_barcode_branch_stock:
    path:     /barcode-wise-branch-stock
    defaults: { _controller: "TallyBundle:StockItem:barcodeBranchStock" }

tally_barcode_stock:
    path:     /barcode-wise-stock
    defaults: { _controller: "TallyBundle:StockItem:barcodeStock" }

tally_barcode_wise_branch_stock:
    path:     /{barcode}/single-barcode-wise-branch-stock
    defaults: { _controller: "TallyBundle:StockItem:singleBarcodeBranchStock" }
    methods:  GET
    options:
            expose: true

