<?php
/**
 * Created by PhpStorm.
 * User: shafiq
 * Date: 9/28/15
 * Time: 10:56 AM
 */

namespace Syndicate\Bundle\ComponentBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Syndicate\Bundle\ComponentBundle\Entity\StudyAbroad;

/**
 * StudyAbroadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudyAbroadRepository extends EntityRepository
{

    public function insertVendor($id)
    {
        $em = $this->_em;
        $entity = $em->getRepository('SyndicateComponentBundle:StudyAbroad')->findOneBy(array('user'=>$id));
        if(empty($entity)){

            $entity = new StudyAbroad();
            $user  = $em->getRepository('UserBundle:User')->find($id);
            $entity->setUser($user);
            $em->persist($entity);
            $em->flush();

        }

    }


    public function setStudyAbroadSyndicate($entity,$syndicates){

        $em = $this->_em;
        if(!empty($entity)){

            $synarr = array();
            foreach($syndicates as $sid ){
                $synarr[] = $em->getRepository('SettingToolBundle:Syndicate')->findOneBy(array('id'=>$sid));
            }
            if (!empty($synarr)) {

                $entity->setSyndicates($synarr);
                $em->persist($entity);
                $em->flush();
            }
        }

    }


}