education_config_manage:
    path:     /manage
    defaults: { _controller: "EducationBundle:Config:manage" }

education_config_update:
    path:     /update
    defaults: { _controller: "EducationBundle:Config:update" }
    methods:  [POST, PUT]

education_restore_master:
    path:     /restore-master-data
    defaults: { _controller: "EducationBundle:Config:restoreMasterParticular" }


