customer_self:
    path:     /
    defaults: { _controller: "CustomerBundle:Student:index" }


customer_edit_profile:
    path:     /edit-profile
    defaults: { _controller: "CustomerBundle:Student:edit" }

customer_edit_profile_update:
    path:     /update-profile
    defaults: { _controller: "CustomerBundle:Student:update" }
    methods:  [POST, PUT]
