dms_config_manage:
    path:     /manage
    defaults: { _controller: "DmsBundle:DmsConfig:manage" }

dms_config_update:
    path:     /update
    defaults: { _controller: "DmsBundle:DmsConfig:update" }
    methods:  [POST, PUT]

