dms_invoice:
    path:     /
    defaults: { _controller: "DmsBundle:Invoice:index" }

dms_invoice_show:
    path:     /{id}/show
    defaults: { _controller: "DmsBundle:Invoice:show" }

dms_invoice_new:
    path:     /new
    defaults: { _controller: "DmsBundle:Invoice:new" }

dms_invoice_admission:
    path:     /admission-new
    defaults: { _controller: "DmsBundle:Invoice:new" }

dms_invoice_edit:
    path:     /{id}/edit
    defaults: { _controller: "DmsBundle:Invoice:edit" }

dms_invoice_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "DmsBundle:Invoice:particularSearch" }

dms_invoice_particular_procedure:
    path:     /{invoice}/{service}/particular-procedure
    defaults: { _controller: "DmsBundle:Invoice:particularProcedure" }
    methods:  POST
    options:
            expose: true

dms_invoice_particular_add:
    path:     /{invoice}/particular-add
    defaults: { _controller: "DmsBundle:Invoice:addParticular" }
    methods:  POST
    options:
            expose: true

dms_invoice_payment:
    path:     /{invoice}/invoice-payment
    defaults: { _controller: "DmsBundle:Invoice:addPayment" }
    methods:  POST
    options:
            expose: true

dms_invoice_medicine_add:
    path:     /{invoice}/medicine-add
    defaults: { _controller: "DmsBundle:Invoice:addMedicine" }
    methods:  POST
    options:
            expose: true

dms_invoice_medicine_delete:
    path:     /{id}/medicine-delete
    defaults: { _controller: "DmsBundle:Invoice:deleteMedicine" }

dms_invoice_treatment_approved:
    path:     /{id}/treatment-approved
    defaults: { _controller: "DmsBundle:Invoice:treatmentApproved" }

dms_invoice_treatment_delete:
    path:     /{invoice}/{id}/treatment-delete
    defaults: { _controller: "DmsBundle:Invoice:treatmentDelete" }

dms_invoice_appointment_datetime_check:
    path:     /treatment-appointment-datetime-check
    defaults: { _controller: "DmsBundle:Invoice:treatmentAppointmentDatetime" }
    methods:  POST
    options:
            expose: true

dms_invoice_appointment_datetime_select:
    path:     /inline-appointment-datetime-select
    defaults: { _controller: "DmsBundle:Invoice:appointmentTime" }
    options:
           expose: true

dms_invoice_discount_update:
    path:     /invoice/invoice-dicount-update
    defaults: { _controller: "DmsBundle:Invoice:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

dms_invoice_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "DmsBundle:Invoice:approve" }
    methods:  POST
    options:
            expose: true

dms_invoice_update:
    path:     /{id}/update
    defaults: { _controller: "DmsBundle:Invoice:update" }
    methods:  [POST, PUT]

dms_invoice_delete:
    path:     /{id}/delete
    defaults: { _controller: "DmsBundle:Invoice:delete" }

dms_invoice_reverse:
    path:     /{invoice}/invoice-reverse-create
    defaults: { _controller: "DmsBundle:Invoice:pathologicalInvoiceReverse" }

dms_invoice_reverse_show:
    path:     /{id}/invoice-reverse-show
    defaults: { _controller: "DmsBundle:Invoice:InvoiceReverseShow" }

dms_invoice_discount_delete:
    path:     /{id}/discount-delete
    defaults: { _controller: "DmsBundle:Invoice:discountDelete" }

dms_invoice_confirm:
    path:     /{id}/invoice-confirm
    defaults: { _controller: "DmsBundle:Invoice:confirm" }

dms_invoice_particular_delete:
    path:     /{invoice}/{id}/particular-delete
    defaults: { _controller: "DmsBundle:Invoice:invoiceParticularDelete" }

dms_invoice_print_invoice:
    path:     /{id}/print
    defaults: { _controller: "DmsBundle:Invoice:invoicePrint" }

dms_invoice_process_update:
    path:     /hms-invoice/upadte-process
    defaults: { _controller: "DmsBundle:Invoice:invoiceProcessUpdate" }
    methods:  POST
    options:
            expose: true

dms_invoice_status_select:
    path:     /invoice-status-select
    defaults: { _controller: "DmsBundle:Invoice:statusSelect" }
    options:
           expose: true

dms_invoice_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "DmsBundle:Invoice:deleteEmptyInvoice" }

dms_invoice_customer_details:
    path:     /invoice-patient-details
    defaults: { _controller: "DomainUserBundle:CustomerHms:details" }
    methods:  POST
    options:
           expose: true

dms_invoice_add_patient:
    path:     /{id}/invoice-patient-add
    defaults: { _controller: "DmsBundle:Invoice:addPatient" }
    methods:  [POST, PUT]
    options:
            expose: true

dms_treatment_inline_update:
    path:     /inline-update
    defaults: { _controller: "DmsBundle:Invoice:inlineUpdate" }


dms_treatment_plan:
    path:     /treatment-plan
    defaults: { _controller: "DmsBundle:TreatmentPlan:index" }

dms_treatment_appointment_schedule:
    path:     /treatment-appointment-date
    defaults: { _controller: "DmsBundle:TreatmentPlan:appointmentDateSchedule" }
    methods:  POST
    options:
           expose: true

dms_treatment_plan_sms:
    path:     /{patient}/{id}/send-sms
    defaults: { _controller: "DmsBundle:TreatmentPlan:sendSmsPlan" }