dms_report_sales_summary:
    path:     /sales-summary
    defaults: { _controller: "DmsBundle:Report:salesSummary" }

dms_report_sales:
    path:     /sales-details
    defaults: { _controller: "DmsBundle:Report:sales" }

dms_report_sales_monthly:
    path:     /monthly-sales-summary
    defaults: { _controller: "DmsBundle:Report:monthlySales" }

dms_report_sales_all_yearly:
    path:     /all-year-sales-summary
    defaults: { _controller: "DmsBundle:Report:allYearlySales" }

dms_report_sales_yearly:
    path:     /yearly-sales-summary
    defaults: { _controller: "DmsBundle:Report:yearlySales" }

dms_report_sales_treatment:
    path:     /treatment-wise-sales
    defaults: { _controller: "DmsBundle:Report:treatmentWiseSales" }

dms_report_purchase_summary:
    path:     /purchase-summary
    defaults: { _controller: "DmsBundle:Report:purchaseSummary" }

dms_report_purchase:
    path:     /purchase-summary
    defaults: { _controller: "DmsBundle:Report:purchaseSummary" }

