inventory_report:
    resource: "@InventoryBundle/Resources/config/routing/report.yml"
    prefix:   /inventory/report

app_setting_bank:
    resource: "@InventoryBundle/Resources/config/routing/appsetting/bankaccount.yml"
    prefix:   /appsetting/bank-account

app_setting_mobile:
    resource: "@InventoryBundle/Resources/config/routing/appsetting/mobileaccount.yml"
    prefix:   /appsetting/mobile-account

app_setting_barnch_shop:
    resource: "@InventoryBundle/Resources/config/routing/appsetting/branchshop.yml"
    prefix:   /appsetting/branch-shop

inventory_excelimproter:
    resource: "@InventoryBundle/Resources/config/routing/excelimporter.yml"
    prefix:   /inventory/excelimproter

inventory_delivery:
    resource: "@InventoryBundle/Resources/config/routing/delivery.yml"
    prefix:   /inventory/delivery

inventory_branch_invoice:
    resource: "@InventoryBundle/Resources/config/routing/branchinvoice.yml"
    prefix:   /inventory/branch-invoice

inventory_salesimport:
    resource: "@InventoryBundle/Resources/config/routing/salesimport.yml"
    prefix:   /inventory/sales-improt

inventory_food_product:
    resource: "@InventoryBundle/Resources/config/routing/foodproduct.yml"
    prefix:   /food/product

inventory_service_item:
    resource: "@InventoryBundle/Resources/config/routing/serviceitem.yml"
    prefix:   /service/item

inventory_service_sales:
    resource: "@InventoryBundle/Resources/config/routing/servicesales.yml"
    prefix:   /service/sales

inventory_goods:
    resource: "@InventoryBundle/Resources/config/routing/goods.yml"
    prefix:   /goods/item

inventory_purchasevendoritem:
    resource: "@InventoryBundle/Resources/config/routing/purchasevendoritem.yml"
    prefix:   /inventory/purchasevendoritem

inventory_salesreturn:
    resource: "@InventoryBundle/Resources/config/routing/salesreturn.yml"
    prefix:   /inventory/salesreturn

inventory_purchasereturn:
    resource: "@InventoryBundle/Resources/config/routing/purchasereturn.yml"
    prefix:   /inventory/purchase/return

inventory_itemattribute:
    resource: "@InventoryBundle/Resources/config/routing/itemattribute.yml"
    prefix:    /inventory/item-attribute

inventory_itembrand:
    resource: "@InventoryBundle/Resources/config/routing/itembrand.yml"
    prefix:    /inventory/brand

inventory_colorsize:
    resource: "@InventoryBundle/Resources/config/routing/colorsize.yml"
    prefix:    /inventory/colorsize

inventory_itemsize:
    resource: "@InventoryBundle/Resources/config/routing/itemsize.yml"
    prefix:    /inventory/item-size

inventory_itemunit:
    resource: "@InventoryBundle/Resources/config/routing/itemunit.yml"
    prefix:    /inventory/item-unit

inventory_itemcolor:
    resource: "@InventoryBundle/Resources/config/routing/itemcolor.yml"
    prefix:    /inventory/item-color

inventory_inventory_product:
    resource: "@InventoryBundle/Resources/config/routing/product.yml"
    prefix:   /inventory/product

inventory_sales:
    resource: "@InventoryBundle/Resources/config/routing/sales.yml"
    prefix:   /inventory/sales

inventory_manual:
    resource: "@InventoryBundle/Resources/config/routing/salesmanual.yml"
    prefix:   /inventory/sales-manual

inventory_salesgeneral:
    resource: "@InventoryBundle/Resources/config/routing/salesgeneral.yml"
    prefix:   /inventory/sales-general

inventory_salescustomer:
    resource: "@InventoryBundle/Resources/config/routing/salesonline.yml"
    prefix:   /inventory/sales-online

inventory_stockitem:
    resource: "@InventoryBundle/Resources/config/routing/stockitem.yml"
    prefix:   /inventory/stockitem

inventory_delivery_return:
    resource: "@InventoryBundle/Resources/config/routing/deliveryreturn.yml"
    prefix:   /inventory/delivery-return

inventory_damage:
    resource: "@InventoryBundle/Resources/config/routing/damage.yml"
    prefix:   /inventory/damage

inventory_purchaseitem:
    resource: "@InventoryBundle/Resources/config/routing/purchaseitem.yml"
    prefix:   /inventory/purchaseitem

inventory_category:
    resource: "@InventoryBundle/Resources/config/routing/category.yml"
    prefix:   /inventory/category

inventory_purchaseorder:
    resource: "@InventoryBundle/Resources/config/routing/purchaseorder.yml"
    prefix:   /inventory/purchaseorder

inventory_purchase:
    resource: "@InventoryBundle/Resources/config/routing/purchase.yml"
    prefix:   /inventory/purchase

inventory_vendor:
    resource: "@InventoryBundle/Resources/config/routing/vendor.yml"
    prefix:   /inventory/vendor

inventory_warehouse:
    resource: "@InventoryBundle/Resources/config/routing/warehouse.yml"
    prefix:   /inventory/warehouse

inventory_item:
    resource: "@InventoryBundle/Resources/config/routing/item.yml"
    prefix:   /inventory/item

inventory_barcode:
    resource: "@InventoryBundle/Resources/config/routing/barcode.yml"
    prefix:   /inventory/barcode

inventory_itemtypegrouping:
    resource: "@InventoryBundle/Resources/config/routing/itemtypegrouping.yml"
    prefix:   /inventory/itemtypegrouping

inventory_inventoryconfig:
    resource: "@InventoryBundle/Resources/config/routing/inventoryconfig.yml"
    prefix:   /inventory/config

stockitem_results:
    path:     /results
    defaults: { _controller: "InventoryBundle:StockItem:indexResults" }
