<?php

namespace Syndicate\Bundle\ComponentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Syndicate\Bundle\ComponentBundle\Entity\Vendor;

/**
 * VendorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorRepository extends EntityRepository
{
    public function insertVendor($id)
    {
        $em = $this->_em;
        $entity = $em->getRepository('SyndicateComponentBundle:Vendor')->findOneBy(array('user'=>$id));
        if(empty($entity)){
            $entity = new Vendor();
            $user  = $em->getRepository('UserBundle:User')->find($id);
            $entity->setUser($user);
            $em->persist($entity);
            $em->flush();
        }


    }


}
