assets_stockitem:
    path:     /
    defaults: { _controller: "AssetsBundle:StockItem:index" }
    options:
        expose: true

assets_stockitem_show:
    path:     /{item}/show
    defaults: { _controller: "AssetsBundle:StockItem:show" }

assets_barcode_branch_stock:
    path:     /barcode-wise-branch-stock
    defaults: { _controller: "AssetsBundle:StockItem:barcodeBranchStock" }

assets_barcode_stock:
    path:     /barcode-wise-stock
    defaults: { _controller: "AssetsBundle:StockItem:barcodeStock" }

assets_barcode_wise_branch_stock:
    path:     /{barcode}/single-barcode-wise-branch-stock
    defaults: { _controller: "AssetsBundle:StockItem:singleBarcodeBranchStock" }
    methods:  GET
    options:
            expose: true