report_controllers:
    resource: '@ReportBundle/Controller/DefaultController.php'
    type: annotation

report_accounting_controllers:
    resource: '@ReportBundle/Controller/AccountingController.php'
    type: annotation