hotel_report:
    resource: "@HotelBundle/Resources/config/routing/report.yml"
    prefix:   /report

hotel_purchase:
    resource: "@HotelBundle/Resources/config/routing/purchase.yml"
    prefix:   /purchase

hotel_vendor:
    resource: "@HotelBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor

hotel_invoice:
    resource: "@HotelBundle/Resources/config/routing/invoice.yml"
    prefix:   /invoice

hotel_stock:
    resource: "@HotelBundle/Resources/config/routing/stock.yml"
    prefix:   /stock

hotel_product:
    resource: "@HotelBundle/Resources/config/routing/product.yml"
    prefix:   /product

hotel_product_production:
    resource: "@HotelBundle/Resources/config/routing/production.yml"
    prefix:   /product-production

hotel_damage:
    resource: "@HotelBundle/Resources/config/routing/damage.yml"
    prefix:   /damage

hotel_category:
    resource: "@HotelBundle/Resources/config/routing/category.yml"
    prefix:   /category

hotel_config:
    resource: "@HotelBundle/Resources/config/routing/config.yml"
    prefix:   /config

hotel_homepage:
    path:     /dashoard
    defaults: { _controller: HotelBundle:Default:index }
