<?php

namespace Appstore\Bundle\AccountingBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * EmployeeSalaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalarySettingRepository extends EntityRepository
{

    public function findWithSearch($globalOption,$data)
    {
        $user = isset($data['user'])? $data['user'] :'';
        $qb = $this->createQueryBuilder('e');
        $qb->where("e.globalOption = :globalOption");
        $qb->setParameter('globalOption', $globalOption);
        if (!empty($user)) {
            $qb->join('e.user','user');
            $qb->andWhere("user.username = :user");
            $qb->setParameter('user', $user);
        }
        $qb->addOrderBy('e.updated','DESC');
        $result = $qb->getQuery();
        return $result;

    }
}
