parameters:
#    mobile.example.class: Mobile\SettingsBundle\Example

services:
#    mobile.example:
#        class: %mobile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

 setting.menuTreeSettingRepo:
        class: Mobile\SettingsBundle\Service\MenuTreeManager
        arguments: [@doctrine]