<?php

namespace Setting\Bundle\AppearanceBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Setting\Bundle\ContentBundle\Entity\Page;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{

    public function createMenuForPage(Page $reEntity = null)
    {
        $entity = new Menu();

        if ($reEntity != null) {

            $entity->setGlobalOption($reEntity->getGlobalOption());
            $entity->setMenu($reEntity->getMenu());
            $entity->setSlug($reEntity->getSlug());
            $entity->setModule($reEntity->getModule());
            $entity->setPage($reEntity);
            $this->getEntityManager()->persist($entity);
            $this->getEntityManager()->flush();
        }
    }

    public function updateMenu($data)
    {

        $em = $this->getEntityManager();
        foreach ($data['id'] as $index => $id ){
            $menu = ($data['menu'][$index]) ? $data['menu'][$index] : Null ;
            $entity = $this->findOneBy(array('id'=>$id));
            if (!empty($entity)) {
                $entity->setMenu($menu);
                $em->persist($entity);
            }
        }
        $em->flush();
    }
}
