home:
    pattern: /
    defaults: { _controller: FrontendBundle:Default:index}

kintethako:
    pattern: /
    defaults: { _controller: FrontendBundle:Ecommerce:index}

domain_receive_email:
    path:     /{subdomain}/email/receive
    defaults: { _controller: FrontendBundle:SmsEmailReceive:smsReceive}

domain_receive_sms:
    path:     /{subdomain}/sms/receive
    defaults: { _controller: FrontendBundle:SmsEmailReceive:emailReceive}

