api_setup:
    path:     /setup
    defaults: { _controller: BinduBundle:Api:setup }


api_system_user:
    path:     /system-user
    defaults: { _controller: BinduBundle:Api:systemUsers }

api_system_stock_item:
    path:     /stock-item
    defaults: { _controller: BinduBundle:Api:stockItem }


api_system_stock_category:
    path:     /stock-category
    defaults: { _controller: BinduBundle:Api:category }


api_system_tarnsaction_method:
    path:     /tarnsaction-method
    defaults: { _controller: BinduBundle:Api:transactionMethod }


api_system_bank:
    path:     /online-bank-acccount
    defaults: { _controller: BinduBundle:Api:apiBank }


api_system_mobile:
    path:     /mobile-account
    defaults: { _controller: BinduBundle:Api:apiMobile }


api_system_customer:
    path:     /anonymiuse-customer
    defaults: { _controller: BinduBundle:Api:customer }


api_system_vendor:
    path:     /vendor
    defaults: { _controller: BinduBundle:Api:vendor }


api_system_unit:
    path:     /product-unit
    defaults: { _controller: BinduBundle:Api:unit }

api_system_dims:
    path:     /medicine-dims
    defaults: { _controller: BinduBundle:Api:medicineDims }


api_system_expense_category:
    path:     /expense-category
    defaults: { _controller: BinduBundle:Api:expenditureCategory }

api_system_template_customization:
    path:     /template-customization
    defaults: { _controller: BinduBundle:Api:templateCustomization }


