api_ecommerce_setup:
    path:     /setup
    defaults: { _controller: BinduBundle:ApiEcommerce:setup }

api_ecommerce_sidebar_menu:
    path:     /sidebar-menu
    defaults: { _controller: BinduBundle:ApiEcommerce:menu }

api_ecommerce_home_feature_slider:
    path:     /home-feature-slider
    defaults: { _controller: BinduBundle:ApiEcommerce:homeFeatureSlider }

api_ecommerce_feature_widget_product:
    path:     /feature-widget-product
    defaults: { _controller: BinduBundle:ApiEcommerce:featureProduct }

api_ecommerce_item_details:
    path:     /product-details
    defaults: { _controller: BinduBundle:ApiEcommerce:productDetails }

api_ecommerce_item:
    path:     /product
    defaults: { _controller: BinduBundle:ApiEcommerce:product }

api_ecommerce_item_global_search:
    path:     /search
    defaults: { _controller: BinduBundle:ApiEcommerce:product }

api_ecommerce_item_search:
    path:     /product-search
    defaults: { _controller: BinduBundle:ApiEcommerce:product }

api_ecommerce_item_category:
    path:     /feature-category
    defaults: { _controller: BinduBundle:ApiEcommerce:category }

api_ecommerce_item_all_category:
    path:     /all-category
    defaults: { _controller: BinduBundle:ApiEcommerce:allCategory }

api_ecommerce_item_brand:
    path:     /feature-brand
    defaults: { _controller: BinduBundle:ApiEcommerce:brand }

api_ecommerce_item_all_brand:
    path:     /all-brand
    defaults: { _controller: BinduBundle:ApiEcommerce:allBrand }

api_ecommerce_item_promotion:
    path:     /promotion
    defaults: { _controller: BinduBundle:ApiEcommerce:promotion }

api_ecommerce_item_tag:
    path:     /tag
    defaults: { _controller: BinduBundle:ApiEcommerce:tag }

api_ecommerce_item_discount:
    path:     /discount
    defaults: { _controller: BinduBundle:ApiEcommerce:discount }

api_ecommerce_testimonial:
    path:     /testimonial
    defaults: { _controller: BinduBundle:ApiEcommerce:testimonial }

api_ecommerce_login:
    path:     /user-login
    defaults: { _controller: BinduBundle:ApiEcommerce:userLogin }
    methods:  POST
    options:
            expose: true

api_ecommerce_registration:
    path:     /user-register
    defaults: { _controller: BinduBundle:ApiEcommerce:userRegister }
    methods:  POST
    options:
            expose: true