api_poskeeper_login:
    path:     /login
    defaults: { _controller: BinduBundle:ApiPoskeeper:login }

api_poskeeper_setup:
    path:     /setup
    defaults: { _controller: BinduBundle:ApiPoskeeper:setup }

api_poskeeper_app:
    path:     /shop-type
    defaults: { _controller: BinduBundle:ApiPoskeeper:apps }

api_poskeeper_register:
    path:     /store-build
    defaults: { _controller: BinduBundle:ApiPoskeeper:storeBuild }

