api_poskeeper_login:
    path:     /otp-login
    defaults: { _controller: BinduBundle:ApiPoskeeper:login }

api_poskeeper_setup:
    path:     /setup
    defaults: { _controller: BinduBundle:ApiPoskeeper:setup }

api_poskeeper_splash:
    path:     /splash
    defaults: { _controller: BinduBundle:ApiPoskeeper:splash }

api_poskeeper_app:
    path:     /shop-type
    defaults: { _controller: BinduBundle:ApiPoskeeper:apps }

api_poskeeper_register:
    path:     /store-build
    defaults: { _controller: BinduBundle:ApiPoskeeper:storeBuild }

api_poskeeper_stock_item:
    path:     /stock-item
    defaults: { _controller: BinduBundle:Api:stockItem }


api_poskeeper_stock_create:
    path:     /stock-create
    defaults: { _controller: BinduBundle:Api:createStock }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_stock_edit:
    path:     /stock-edit
    defaults: { _controller: BinduBundle:Api:stockEdit }

api_poskeeper_stock_update:
    path:     /stock-update
    defaults: { _controller: BinduBundle:Api:stockUpdate }
    methods:  POST
    options:
        expose: true

api_poskeeper_stock_delete:
    path:     /stock-delete
    defaults: { _controller: BinduBundle:Api:stockDelete }

api_poskeeper_customer_create:
    path:     /customer-create
    defaults: { _controller: BinduBundle:Api:createCustomer }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_customer_update:
    path:     /customer-update
    defaults: { _controller: BinduBundle:Api:updateCustomer }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_customer_ledger:
    path:     /customer-ledeger
    defaults: { _controller: BinduBundle:Api:customerLedger }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_customer_invoice_details:
    path:     /customer-invoice-details
    defaults: { _controller: BinduBundle:Api:customerInvoice }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_sales_payment:
    path:     /payment-receive
    defaults: { _controller: BinduBundle:Api:salesReceive }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_create:
    path:     /vendor-create
    defaults: { _controller: BinduBundle:Api:createVendor }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_update:
    path:     /vendor-update
    defaults: { _controller: BinduBundle:Api:updateVendor }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_ledger:
    path:     /vendor-ledeger
    defaults: { _controller: BinduBundle:Api:vendorLedger }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_invoice_details:
    path:     /vendor-invoice-details
    defaults: { _controller: BinduBundle:Api:vendorInvoice }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_payment:
    path:     /payment
    defaults: { _controller: BinduBundle:Api:purchasePayment }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_short_list:
    path:     /purchase-short-list
    defaults: { _controller: BinduBundle:Api:purchaseShortList }

api_poskeeper_instant_purchase:
    path:     /instant-purchase-item
    defaults: { _controller: BinduBundle:Api:instantPurchase }

api_poskeeper_add_purchase_shortlist:
    path:     /add-purchase-short-list
    defaults: { _controller: BinduBundle:Api:insertPurchaseShortItem }


