api_poskeeper_login:
    path:     /poskeeper/otp-login
    defaults: { _controller: BinduBundle:ApiPoskeeper:login }

api_poskeeper_setup:
    path:     /poskeeper/setup
    defaults: { _controller: BinduBundle:ApiPoskeeper:setup }

api_poskeeper_app:
    path:     /poskeeper/shop-type
    defaults: { _controller: BinduBundle:ApiPoskeeper:apps }

api_poskeeper_register:
    path:     /poskeeper/store-build
    defaults: { _controller: BinduBundle:ApiPoskeeper:storeBuild }

api_poskeeper_stock_create:
    path:     /poskeeper/stock-create
    defaults: { _controller: BinduBundle:Api:createStock }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_stock_edit:
    path:     /poskeeper/stock-edit
    defaults: { _controller: BinduBundle:Api:stockEdit }

api_poskeeper_stock_update:
    path:     /poskeeper/stock-update
    defaults: { _controller: BinduBundle:Api:stockUpdate }
    methods:  POST
    options:
        expose: true

api_poskeeper_stock_delete:
    path:     /poskeeper/stock-delete
    defaults: { _controller: BinduBundle:Api:stockDelete }

api_poskeeper_customer_create:
    path:     /poskeeper/customer-create
    defaults: { _controller: BinduBundle:Api:createCustomer }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_customer_update:
    path:     /poskeeper/customer-update
    defaults: { _controller: BinduBundle:Api:updateCustomer }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_customer_ledger:
    path:     /poskeeper/customer-ledeger
    defaults: { _controller: BinduBundle:Api:customerLedger }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_customer_invoice_details:
    path:     /poskeeper/customer-invoice-details
    defaults: { _controller: BinduBundle:Api:customerInvoice }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_sales_payment:
    path:     /poskeeper/payment-receive
    defaults: { _controller: BinduBundle:Api:salesReceive }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_create:
    path:     /poskeeper/vendor-create
    defaults: { _controller: BinduBundle:Api:createVendor }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_update:
    path:     /poskeeper/vendor-update
    defaults: { _controller: BinduBundle:Api:updateVendor }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_ledger:
    path:     /poskeeper/vendor-ledeger
    defaults: { _controller: BinduBundle:Api:vendorLedger }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_invoice_details:
    path:     /poskeeper/vendor-invoice-details
    defaults: { _controller: BinduBundle:Api:vendorInvoice }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_payment:
    path:     /poskeeper/payment
    defaults: { _controller: BinduBundle:Api:purchasePayment }
    methods:  POST|GET
    options:
        expose: true


api_poskeeper_short_list:
    path:     /poskeeper/purchase-short-list
    defaults: { _controller: BinduBundle:Api:purchaseShortList }

api_poskeeper_short_list:
    path:     /poskeeper/instant-purchase-item
    defaults: { _controller: BinduBundle:Api:instantPurchase }

api_poskeeper_add_purchase_shortlist:
    path:     /poskeeper/add-purchase-short-list
    defaults: { _controller: BinduBundle:Api:insertPurchaseShortItem }