api_system_license_verify:
    path:     /license-verify
    defaults: { _controller: BinduBundle:ApiPoskeeper:licenseVerify }

api_system_app:
    path:     /shop-type
    defaults: { _controller: BinduBundle:ApiPoskeeper:apps }

api_system_register:
    path:     /store-build
    defaults: { _controller: BinduBundle:ApiPoskeeper:storeBuild }

api_system_dashboard:
    path:     /dashboard
    defaults: { _controller: BinduBundle:ApiPoskeeper:dashboard }

api_system_multi_user:
    path:     /multi-user
    defaults: { _controller: BinduBundle:ApiPoskeeper:multiUser }

api_system_create_user:
    path:     /create-user
    defaults: { _controller: BinduBundle:ApiPoskeeper:createUser }

api_system_edit_user:
    path:     /edit-user
    defaults: { _controller: BinduBundle:ApiPoskeeper:editUser }

api_system_update_user:
    path:     /update-user
    defaults: { _controller: BinduBundle:ApiPoskeeper:updateUser }

api_system_check_user_duplicate:
    path:     /check-duplicate-user-name
    defaults: { _controller: BinduBundle:ApiPoskeeper:checkDuplicateUser }

api_system_user_login:
    path:     /user-login
    defaults: { _controller: BinduBundle:ApiPoskeeper:login }

api_system_user_forget_password:
    path:     /user-forget-password
    defaults: { _controller: BinduBundle:ApiPoskeeper:forgetPassword }

api_system_user_reset_password:
    path:     /user-reset-password
    defaults: { _controller: BinduBundle:ApiPoskeeper:resetPassword }

api_system_user:
    path:     /system-user
    defaults: { _controller: BinduBundle:ApiPoskeeper:systemUsers }

api_system_stock_item:
    path:     /stock-item
    defaults: { _controller: BinduBundle:ApiPoskeeper:stockItem }


api_system_stock_category:
    path:     /stock-category
    defaults: { _controller: BinduBundle:ApiPoskeeper:category }


api_system_stock_create:
    path:     /stock-create
    defaults: { _controller: BinduBundle:ApiPoskeeper:createStock }

api_system_stock_edit:
    path:     /stock-edit
    defaults: { _controller: BinduBundle:ApiPoskeeper:stockEdit }


api_system_stock_update:
    path:     /stock-update
    defaults: { _controller: BinduBundle:ApiPoskeeper:updateStock }

api_system_stock_measurment:
    path:     /measurment-create
    defaults: { _controller: BinduBundle:ApiPoskeeper:insertAndroidStockMeasurement }

api_system_stock_measurment_delete:
    path:     /measurment-delete
    defaults: { _controller: BinduBundle:ApiPoskeeper:deleteAndroidStockMeasurement }


api_system_tarnsaction_method:
    path:     /tarnsaction-method
    defaults: { _controller: BinduBundle:ApiPoskeeper:transactionMethod }

api_system_payment_card:
    path:     /payment-card
    defaults: { _controller: BinduBundle:ApiPoskeeper:paymentCard }


api_system_bank:
    path:     /online-bank-acccount
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiBank }


api_system_mobile:
    path:     /mobile-account
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiMobile }


api_system_customer:
    path:     /anonymiuse-customer
    defaults: { _controller: BinduBundle:ApiPoskeeper:customer }

api_system_vendor:
    path:     /vendor
    defaults: { _controller: BinduBundle:ApiPoskeeper:vendor }

api_system_short_list:
    path:     /purchase-short-list
    defaults: { _controller: BinduBundle:ApiPoskeeper:purchaseShortList }

api_system_add_purchase_shortlist:
    path:     /add-purchase-short-list
    defaults: { _controller: BinduBundle:ApiPoskeeper:insertPurchaseShortItem }

delete-purchase-short-list:
    path:     /delete-purchase-short-list
    defaults: { _controller: BinduBundle:ApiPoskeeper:deletePurchaseShortItem }

api_system_add_global_to_local:
    path:     /add-global-to-local
    defaults: { _controller: BinduBundle:ApiPoskeeper:insertGlobalToLocal }

api_system_unit:
    path:     /product-unit
    defaults: { _controller: BinduBundle:ApiPoskeeper:unit }

api_system_medicine:
    path:     /medicine
    defaults: { _controller: BinduBundle:ApiPoskeeper:medicineName }

api_system_purchase:
    path:     /purchase
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiPurchase }


api_system_add_purchase:
    path:     /add-purchase
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiAddPurchase }
    methods:  POST
    options:
        expose: true

api_system_purchase_item:
    path:     /purchase-item
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiPurchaseItem }
    methods:  POST
    options:
        expose: true

api_system_medicine_generic:
    path:     /medicine-generic
    defaults: { _controller: BinduBundle:ApiPoskeeper:medicinegeneric }

api_system_medicine_form:
    path:     /medicine-form
    defaults: { _controller: BinduBundle:ApiPoskeeper:medicineForm }

api_system_medicine_strength:
    path:     /medicine-strength
    defaults: { _controller: BinduBundle:ApiPoskeeper:medicineStrength }

api_system_medicine_manuficture:
    path:     /medicine-menuficture
    defaults: { _controller: BinduBundle:ApiPoskeeper:medicineMenuficture }

api_system_dims:
    path:     /medicine-global
    defaults: { _controller: BinduBundle:ApiPoskeeper:medicineGlobal }

api_system_expense_category:
    path:     /expense-category
    defaults: { _controller: BinduBundle:ApiPoskeeper:expenditureCategory }


api_system_sales:
    path:     /sales
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiSales }
    methods:  POST
    options:
        expose: true

api_system_sales_item:
    path:     /sales-item
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiSalesItem }
    methods:  POST
    options:
        expose: true

api_system_expense:
    path:     /expense
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiExpense }
    methods:  POST
    options:
        expose: true
