accounting_account_sales_hotel:
    resource: "@AccountingBundle/Resources/config/routing/accounthotel.yml"
    prefix:   /hotel

accounting_account_sales_hospital:
    resource: "@AccountingBundle/Resources/config/routing/accounthospital.yml"
    prefix:   /hms

accounting_account_medicine:
    resource: "@AccountingBundle/Resources/config/routing/accountmedicine.yml"
    prefix:   /medicine

accounting_account_sales_restaurant:
    resource: "@AccountingBundle/Resources/config/routing/accountrestaurant.yml"
    prefix:   /restaurant

accounting_account_sales_adjustment:
    resource: "@AccountingBundle/Resources/config/routing/accountsalesadjustment.yml"
    prefix:   /sales-adjustment

accounting_account_purchase_commission:
    resource: "@AccountingBundle/Resources/config/routing/purchasecommission.yml"
    prefix:   /sales-adjustment

accounting_account_business:
    resource: "@AccountingBundle/Resources/config/routing/accountbusiness.yml"
    prefix:   /business

accounting_report:
    resource: "@AccountingBundle/Resources/config/routing/accountreport.yml"
    prefix:   /report

accounting_hms_report:
    resource: "@AccountingBundle/Resources/config/routing/hmsaccountreport.yml"
    prefix:   /report-hms

accounting_expensecategory:
    resource: "@AccountingBundle/Resources/config/routing/expensecategory.yml"
    prefix:   /expensecategory

accounting_paymentsalary:
    resource: "@AccountingBundle/Resources/config/routing/paymentsalary.yml"
    prefix:   /paymentsalary

accounting_salarysetting:
    resource: "@AccountingBundle/Resources/config/routing/salarysetting.yml"
    prefix:   /salary-invoice

accounting_journal:
    resource: "@AccountingBundle/Resources/config/routing/accountjournal.yml"
    prefix:   /journal

accounting_balancetransfer:
    resource: "@AccountingBundle/Resources/config/routing/accountbalancetransfer.yml"
    prefix:   /balance-transfer

accounting_expenditure:
    resource: "@AccountingBundle/Resources/config/routing/expenditure.yml"
    prefix:   /expenditure

accounting_bank:
    resource: "@AccountingBundle/Resources/config/routing/accountbank.yml"
    prefix:   /bank

accounting_pettycash:
    resource: "@AccountingBundle/Resources/config/routing/pettycash.yml"
    prefix:   /pettycash

accounting_transaction:
    resource: "@AccountingBundle/Resources/config/routing/transaction.yml"
    prefix:   /transaction

accounting_accounthead:
    resource: "@AccountingBundle/Resources/config/routing/accounthead.yml"
    prefix:   /accounthead

accounting_accountbank:
    resource: "@AccountingBundle/Resources/config/routing/accountbank.yml"
    prefix:   /bank-account

accounting_accountmobilebank:
    resource: "@AccountingBundle/Resources/config/routing/accountmobilebank.yml"
    prefix:   /mobile-bank-account

accounting_account_purchase:
    resource: "@AccountingBundle/Resources/config/routing/accountpurchase.yml"
    prefix:   /purchase

accounting_account_sales:
    resource: "@AccountingBundle/Resources/config/routing/accountsales.yml"
    prefix:   /sales

accounting_account_online_order:
    resource: "@AccountingBundle/Resources/config/routing/accountonlineorder.yml"
    prefix:   /online-order


accounting_account_report:
    resource: "@AccountingBundle/Resources/config/routing/report.yml"
    prefix:   /report

accounting_vendor:
    resource: "@AccountingBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor

accounting_print:
    resource: "@AccountingBundle/Resources/config/routing/print.yml"
    prefix:   /print

accounting_migration_sales:
    defaults: { _controller: "AccountingBundle:Default:salesMigration" }
    path:   /migration-sales

accounting_migration_vendor:
    defaults: { _controller: "AccountingBundle:Default:vendorMigration" }
    path:   /migration-vendor

accounting_migration_account_purchase:
    defaults: { _controller: "AccountingBundle:Default:purchaseMigration" }
    path:   /migration-purchase

report_vendor_outstanding:
    path:     /vendor/outstanding
    defaults: { _controller: "AccountingBundle:Report:vendorOutstanding" }

report_vendor_outstanding_pdf:
    path:     /vendor/outstanding-pdf
    defaults: { _controller: "AccountingBundle:Report:vendorOutstandingPdf" }

report_vendor_ledger:
    path:     /vendor/ledger
    defaults: { _controller: "AccountingBundle:Report:vendorLedger" }

report_customer_outstanding:
    path:     /customer/outstanding
    defaults: { _controller: "AccountingBundle:Report:customerOutstanding" }

report_customer_outstanding_pdf:
    path:     /customer/outstanding-pdf
    defaults: { _controller: "AccountingBundle:Report:customerOutstandingPdf" }

report_customer_ledger:
    path:     /customer/ledger
    defaults: { _controller: "AccountingBundle:Report:customerLedger" }



