inventory_barcode:
    path:     /
    defaults: { _controller: "InventoryBundle:Barcode:index" }

barcode_add:
    path:     /add
    defaults: { _controller: "InventoryBundle:Barcode:add" }

barcode_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:Barcode:add" }


barcode_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:Barcode:create" }
    options:
           expose: true

barcode_print:
    path:     /print
    defaults: { _controller: "InventoryBundle:Barcode:print" }
