itemtypegrouping:
    path:     /
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:index" }

itemtypegrouping_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:show" }

itemtypegrouping_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:new" }

itemtypegrouping_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:create" }
    methods:  POST

itemtypegrouping_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:edit" }

itemtypegrouping_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:update" }
    methods:  [POST, PUT]

itemtypegrouping_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:delete" }
    methods:  [POST, DELETE]
