itemsize:
    path:     /
    defaults: { _controller: "InventoryBundle:ItemSize:index" }

inventory_itemsize_search:
    path:     /search
    defaults: { _controller: "InventoryBundle:ItemSize:autoSearch" }
    options:
            expose: true

inventory_itemsize_name:
    path:      /{size}/size-name
    defaults: { _controller: "InventoryBundle:ItemSize:searchItemSizeName" }
    options:
            expose: true

itemsize_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:ItemSize:show" }

itemsize_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:ItemSize:new" }

itemsize_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:ItemSize:create" }
    methods:  POST

itemsize_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:ItemSize:edit" }

itemsize_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:ItemSize:update" }
    methods:  [POST, PUT]

itemsize_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:ItemSize:delete" }
    methods:  [POST, DELETE]
