itemtypegrouping:
    path:     /
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:index" }

itemtypegrouping_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:create" }
    methods:  POST

itemtypegrouping_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:edit" }

itemtypegrouping_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:update" }
    methods:  [POST, PUT]

itemtypegrouping_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:delete" }
    methods:  [POST, DELETE]


inventory_category_search:
    path:     /search
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:autoSearch" }
    options:
            expose: true

inventory_category_name:
    path:      /{category}/vendor-name
    defaults: { _controller: "InventoryBundle:ItemTypeGrouping:searchVendorName" }
    options:
            expose: true