inventory_pos:
    path:     /
    defaults: { _controller: "InventoryBundle:Pos:index" }

inventory_pos_stock_item:
    path:     /pos-stock-item
    defaults: { _controller: "InventoryBundle:Pos:posItems" }
    methods:  GET
    options:
        expose: true

inventory_pos_item_add:
    path:     /{product}/add-to-cart
    defaults: { _controller: "InventoryBundle:Pos:productCart" }


inventory_pos_item_update:
    path:     /{product}/update-to-cart
    defaults: { _controller: "InventoryBundle:Pos:productUpdateCart" }

inventory_pos_item_remove:
    path:     /{product}/remove-to-cart
    defaults: { _controller: "InventoryBundle:Pos:productRemoveCart" }

inventory_pos_update:
    path:     /cart-update
    defaults: { _controller: "InventoryBundle:Pos:update" }
    methods:  [POST, PUT]
    options:
        expose: true

inventory_pos_item:
    path:     /sales-item
    defaults: { _controller: "InventoryBundle:Pos:salesItem" }


inventory_pos_item_purchase:
    path:     /item-purchase-details
    defaults: { _controller: "InventoryBundle:Pos:itemPurchaseDetails" }
    methods:  POST
    options:
            expose: true


inventory_branch_stock_item:
    path:     /{item}/branch-stock-item-details
    defaults: { _controller: "InventoryBundle:Pos:branchStockItemDetails" }
    methods:  GET
    options:
            expose: true

inventory_pos_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:Pos:show" }

inventory_pos_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:Pos:new" }

inventory_pos_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:Pos:new" }


inventory_pos_edit:
    path:     /{code}/pos
    defaults: { _controller: "InventoryBundle:Pos:edit" }

inventory_pos_print:
    path:     /{code}/print
    defaults: { _controller: "InventoryBundle:Pos:print" }

inventory_pos_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "InventoryBundle:Pos:invoicePrint" }

inventory_pos_print_chalan:
    path:     /{invoice}/chalan
    defaults: { _controller: "InventoryBundle:Pos:chalanPrint" }

inventory_pos_discount_update:
    path:     /sales/discount-update
    defaults: { _controller: "InventoryBundle:Pos:salesDiscountUpdate" }
    methods:  POST
    options:
            expose: true


inventory_pos_approve:
    path:     /{id}/approve
    defaults: { _controller: "InventoryBundle:Pos:approve" }
    options:
           expose: true



inventory_pos_reset:
    path:     /{id}/reset
    defaults: { _controller: "InventoryBundle:Pos:reset" }

inventory_pos_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:Pos:delete" }

inventory_pos_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "InventoryBundle:Pos:deleteEmptyInvoice" }

inventory_positem_delete:
    path:     /{sales}/{salesItem}/delete
    defaults: { _controller: "InventoryBundle:Pos:itemDelete" }

inventory_pos_item_serial_update:
    path:     /{salesItem}/update-serial-no
    defaults: { _controller: "InventoryBundle:Pos:itemSerialNoUpdate" }

inventory_pos_inline_update:
    path:     /sales/inline-update
    defaults: { _controller: "InventoryBundle:Pos:salesInlineUpdate" }
    methods:  POST
    options:
            expose: true

inventory_pos_inline_process_update:
    path:     /sales/inline-process-update
    defaults: { _controller: "InventoryBundle:Pos:salesInlineProcessUpdate" }
    methods:  POST
    options:
            expose: true

inventory_pos_inline_status_select:
    path:     /inline-status-select
    defaults: { _controller: "InventoryBundle:Pos:salesSelect" }
    options:
           expose: true

inventory_pos_mobile_update:
    path:     /sales/mobile-update
    defaults: { _controller: "InventoryBundle:Pos:salesInlineMobileUpdate" }
    methods:  POST
    options:
            expose: true

inventory_pos_invoice_search:
    path:     /sales-invoice-sesrch
    defaults: { _controller: "InventoryBundle:Pos:salesInvoiceSearch" }
    options:
           expose: true

inventory_pos_invoice_name:
    path:      /{invoice}/sales-invoice
    defaults: { _controller: "InventoryBundle:Pos:searchSalesInvoiceName" }
    options:
            expose: true