purchaseitemattribute:
    path:     /
    defaults: { _controller: "InventoryBundle:PurchaseItemAttribute:index" }

purchaseitemattribute_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:PurchaseItemAttribute:show" }

purchaseitemattribute_new:
    path:     /{purchaseItem}/new
    defaults: { _controller: "InventoryBundle:PurchaseItemAttribute:new" }

purchaseitemattribute_create:
    path:     /{purchaseItem}/create
    defaults: { _controller: "InventoryBundle:PurchaseItemAttribute:create" }
    methods:  POST

purchaseitemattribute_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:PurchaseItemAttribute:edit" }

purchaseitemattribute_status:
    path:     /{id}/status
    defaults: { _controller: "InventoryBundle:PurchaseItemAttribute:status" }

purchaseitemattribute_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:PurchaseItemAttribute:update" }
    methods:  [POST, PUT]

purchaseitemattribute_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:PurchaseItemAttribute:delete" }
    methods:  [POST, DELETE]
