inventory_salesmanual:
    path:     /
    defaults: { _controller: "InventoryBundle:SalesManual:index" }

inventory_salesmanual_customer:
    path:     /customer
    defaults: { _controller: "InventoryBundle:SalesManual:customer" }

inventory_salesmanual_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:SalesManual:show" }


inventory_salesmanual_insert_item:
    path:    /{sales}/insert-sales-item
    defaults: { _controller: "InventoryBundle:SalesManual:insertManualSalesItem" }
    methods:  [POST]


inventory_salesmanual_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:SalesManual:new" }

inventory_salesmanual_item_search:
    path:     /search
    defaults: { _controller: "InventoryBundle:SalesManual:search" }
    methods:  POST
    options:
            expose: true

inventory_salesmanual_edit:
    path:     /{code}/manual-sales
    defaults: { _controller: "InventoryBundle:SalesManual:edit" }

inventory_salesmanual_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:SalesManual:update" }
    methods:  [POST, PUT]

inventory_salesmanual_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "InventoryBundle:SalesManual:invoicePrint" }

inventory_salesmanual_empty_delete:
    path:     /delete/empty-manual-invoice
    defaults: { _controller: "InventoryBundle:SalesManual:deleteEmptyInvoice" }

inventory_salesmanual_item_inline_update:
    path:     /{salesItem}/manual-sales-item-update
    defaults: { _controller: "InventoryBundle:SalesManual:salesItemUpdate" }
    options:
           expose: true

