inventory_salescustomer:
    path:     /
    defaults: { _controller: "InventoryBundle:SalesCustomer:index" }

inventory_salescustomer_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:SalesCustomer:show" }

inventory_salescustomer_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:SalesCustomer:new" }

inventory_salescustomer_edit:
    path:     /{code}/pos
    defaults: { _controller: "InventoryBundle:SalesCustomer:edit" }

inventory_salescustomer_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:SalesCustomer:update" }
    methods:  [POST, PUT]

inventory_salescustomer_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "InventoryBundle:SalesCustomer:invoicePrint" }

inventory_salescustomer_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "InventoryBundle:SalesCustomer:deleteEmptyInvoice" }