services:
#    appstore_inventory.example:
#        class: Appstore\Bundle\InventoryBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    appstore.product.asset.event.listener:
        class: Appstore\Bundle\AssetsBundle\EventListener\ProductListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.disposal.asset.event.listener:
        class: Appstore\Bundle\AssetsBundle\EventListener\DisposalListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.assets.item.event.listener:
        class: Appstore\Bundle\AssetsBundle\EventListener\ItemListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.assets.purchase.event.listener:
        class: Appstore\Bundle\AssetsBundle\EventListener\PurchaseListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.assets.sales.event.listener:
        class: Appstore\Bundle\AssetsBundle\EventListener\SalesListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }


    appstore.assets.purchase.item.event.listener:
        class: Appstore\Bundle\AssetsBundle\EventListener\PurchaseItemListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }


    appstore.tally.item.event.listener:
        class: Appstore\Bundle\TallyBundle\EventListener\ItemListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.tally.purchase.event.listener:
        class: Appstore\Bundle\TallyBundle\EventListener\PurchaseListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.tally.sales.event.listener:
        class: Appstore\Bundle\TallyBundle\EventListener\SalesListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.tally.purchase.item.event.listener:
        class: Appstore\Bundle\TallyBundle\EventListener\PurchaseItemListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.tally.tariff.import:
        class: Appstore\Bundle\TallyBundle\Importer\TariffExcel
        calls:
              - [ setContainer, [ @service_container ] ]

    appstore_tally.importer.tariff.import:
        class: Appstore\Bundle\TallyBundle\Importer\TariffDataReader
        arguments: [ @phpexcel ]

