
ecommerce_ecommercetemplate:
    resource: "@EcommerceBundle/Resources/config/routing/template.yml"
    prefix:   /ecommerce/template

ecommerce_ecommercehome:
    resource: "@EcommerceBundle/Resources/config/routing/ecommercehome.yml"
    prefix:   /ecommerce/home

ecommerce_ecommerceslider:
    resource: "@EcommerceBundle/Resources/config/routing/ecommerceslider.yml"
    prefix:   /ecommerce/slider

ecommerce_promotion:
    resource: "@EcommerceBundle/Resources/config/routing/promotion.yml"
    prefix:   /ecommerce/promotion

eecommerce_discount:
    resource: "@EcommerceBundle/Resources/config/routing/discount.yml"
    prefix:   /ecommerce/discount

ecommerce_ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing/ecommerce.yml"
    prefix:   /ecommerce/product

ecommerce_config:
    resource: "@EcommerceBundle/Resources/config/routing/ecommerceconfig.yml"
    prefix:   /ecommerce/config

ecommerce_ecommerce_order:
    resource: "@EcommerceBundle/Resources/config/routing/order.yml"
    prefix:   /ecommerce/order

ecommerce_ecommerce_preorder:
    resource: "@EcommerceBundle/Resources/config/routing/preorder.yml"
    prefix:   /ecommerce/preorder

