ecommerce_ecommercehome:
    resource: "@EcommerceBundle/Resources/config/routing/ecommercehome.yml"
    prefix:   /e-commerce/home

ecommerce_promotion:
    resource: "@EcommerceBundle/Resources/config/routing/promotion.yml"
    prefix:   /e-commerce/promotion

eecommerce_discount:
    resource: "@EcommerceBundle/Resources/config/routing/discount.yml"
    prefix:   /e-commerce/discount

ecommerce_ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing/ecommerce.yml"
    prefix:   /e-commerce/product

ecommerce_config:
    resource: "@EcommerceBundle/Resources/config/routing/ecommerceconfig.yml"
    prefix:   /e-commerce/config

ecommerce_ecommerce_order:
    resource: "@EcommerceBundle/Resources/config/routing/order.yml"
    prefix:   /e-commerce/order

ecommerce_ecommerce_preorder:
    resource: "@EcommerceBundle/Resources/config/routing/preorder.yml"
    prefix:   /e-commerce/preorder

