services:
#    appstore_ecommerce.example:
#        class: Appstore\Bundle\EcommerceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    appstore.preorder.event.listener:
        class: Appstore\Bundle\EcommerceBundle\EventListener\PreOrderListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.order.event.listener:
        class: Appstore\Bundle\EcommerceBundle\EventListener\OrderListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.item.event.listener:
        class: Appstore\Bundle\EcommerceBundle\EventListener\ItemListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }