election_member:
    path:     /
    defaults: { _controller: "ElectionBundle:Member:index" }

election_member_new:
    path:     /new
    defaults: { _controller: "ElectionBundle:Member:new" }

election_member_create:
    path:     /create
    defaults: { _controller: "ElectionBundle:Member:create" }
    methods:  POST

election_member_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElectionBundle:Member:edit" }

election_member_show:
    path:     /{id}/show
    defaults: { _controller: "ElectionBundle:Member:show" }

election_member_update:
    path:     /{id}/update
    defaults: { _controller: "ElectionBundle:Member:update" }
    methods:  [POST, PUT]

election_member_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElectionBundle:Member:delete" }

election_member_family:
    path:     /{id}/add-family
    defaults: { _controller: "ElectionBundle:Member:family" }

election_member_family_delete:
    path:     /{id}/add-family
    defaults: { _controller: "ElectionBundle:Member:familyMemberDelete" }

election_member_family_add:
    path:     /{id}/add-family
    defaults: { _controller: "ElectionBundle:Member:familyMemberAdd" }

