tutor:
    path:     /
    defaults: { _controller: "SyndicateComponentBundle:Tutor:index" }

tutor_show:
    path:     /{id}/show
    defaults: { _controller: "SyndicateComponentBundle:Tutor:show" }

tutor_new:
    path:     /new
    defaults: { _controller: "SyndicateComponentBundle:Tutor:new" }

tutor_create:
    path:     /create
    defaults: { _controller: "SyndicateComponentBundle:Tutor:create" }
    methods:  POST

tutor_edit:
    path:     /{id}/edit
    defaults: { _controller: "SyndicateComponentBundle:Tutor:edit" }

tutor_update:
    path:     /{id}/update
    defaults: { _controller: "SyndicateComponentBundle:Tutor:update" }
    methods:  [POST, PUT]

tutor_delete:
    path:     /{id}/delete
    defaults: { _controller: "SyndicateComponentBundle:Tutor:delete" }
    methods:  [POST, DELETE]

tutor_modify:
    path:     /modify
    defaults: { _controller: "SyndicateComponentBundle:Tutor:modify" }

tutor_status:
    path:     /{id}/status
    defaults: { _controller: "SyndicateComponentBundle:Tutor:status" }

tutor_print:
    path:     /{id}/print-details
    defaults: { _controller: "SyndicateComponentBundle:Tutor:printDetails" }

tutor_pdf:
    path:     /{id}/pdf-details
    defaults: { _controller: "SyndicateComponentBundle:Tutor:pdfDetails" }
