tutorial-author:
    path:     /
    defaults: { _controller: "SyndicateComponentBundle:Tutorial:index" }

tutorial-author_show:
    path:     /{id}/show
    defaults: { _controller: "SyndicateComponentBundle:Tutorial:show" }

tutorial-author_new:
    path:     /new
    defaults: { _controller: "SyndicateComponentBundle:Tutorial:new" }

tutorial-author_create:
    path:     /create
    defaults: { _controller: "SyndicateComponentBundle:Tutorial:create" }
    methods:  POST

tutorial-author_edit:
    path:     /{id}/edit
    defaults: { _controller: "SyndicateComponentBundle:Tutorial:edit" }

tutorial-author_update:
    path:     /{id}/update
    defaults: { _controller: "SyndicateComponentBundle:Tutorial:update" }
    methods:  [POST, PUT]

tutorial-author_delete:
    path:     /{id}/delete
    defaults: { _controller: "SyndicateComponentBundle:Tutorial:delete" }
    methods:  [POST, DELETE]
