ecommercesubdomain:
    path:     /
    defaults: { _controller: FrontendBundle:WebService:index }

webservice_product_details:
    path:     /{subdomain}/product/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productDetails }

webservice_product_modal:
    path:     /{subdomain}/product-modal/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productModal }

webservice_product_checkout:
    path:     /{subdomain}/product-check-our
    defaults: { _controller: FrontendBundle:WebServiceProduct:checkout }

webservice_product_cart:
    path:     /{subdomain}/cart/{product}/{subitem}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productAddCart }
    methods:  POST
    options:
            expose: true

webservice_product_wishlist:
    path:     /{subdomain}/wishlist/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productAddWishList }

webservice_product_sub_item:
    path:     /{subdomain}/sub-item/{product}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productSubProduct }

webservice_product_sub_item_cart:
    path:     /{subdomain}/sub-item/{product}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productSubProductCart }

webservice_module_page:
    path:     /{subdomain}/{module}/{slug}
    defaults: { _controller: FrontendBundle:WebServiceModule:modulePage }

webservice_module_category:
    path:     /{subdomain}/category/{module}/{slug}
    defaults: { _controller: FrontendBundle:WebServiceModule:moduleCategory }


webservice_contact:
    path:     /{subdomain}/contact
    defaults: { _controller: FrontendBundle:WebServiceModule:contact }

webservice_product_cart_details:
    path:     /{subdomain}/cart-details
    defaults: { _controller: FrontendBundle:WebServiceProduct:productCart }

webservice_product:
    path:     /{subdomain}/product
    defaults: { _controller: FrontendBundle:WebServiceProduct:product }

webservice_customer_register:
    path:     /{subdomain}/register
    defaults: { _controller: FrontendBundle:WebServiceCustomer:register }

webservice_customer_create:
    path:     /{subdomain}/customer-registration-create
    defaults: { _controller: FrontendBundle:WebServiceCustomer:create }

webservice_customer_confirm:
    path:     /{subdomain}/customer-registration-confirm
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }

webservice_customer_login:
    path:     /{subdomain}/customer-login
    defaults: { _controller:  FrontendBundle:WebServiceCustomer:domainLogin }

webservice_login:
    path:     /{subdomain}/customer-login
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }

webservice_module:
    path:     /{subdomain}/{module}
    defaults: { _controller: FrontendBundle:WebServiceModule:module }

