ecommercesubdomain:
    path:     /
    defaults: { _controller: FrontendBundle:WebService:index }

webservice_sms_receive:
    path:     /receive/sms
    defaults: { _controller: FrontendBundle:SmsEmailReceive:smsReceive}

webservice_email_receive:
    path:     /receive/email
    defaults: { _controller: FrontendBundle:SmsEmailReceive:emailReceive}
    methods:  POST


webservice_product_details:
    path:     /product/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productDetails }

webservice_product_modal:
    path:     /product-modal/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productModal }


webservice_product_cart:
    path:     /cart/{product}/{subitem}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productAddCart }
    methods:  POST
    options:
            expose: true

webservice_product_cart_update:
    path:     /cart/product-update/{cartid}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productUpdateCart }
    methods:  GET
    options:
            expose: true

webservice_product_cart_remove:
    path:      /cart/product-remove/{cartid}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productRemoveCart }

webservice_product_wishlist:
    path:     /wishlist/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productAddWishList }

webservice_product_sub_item:
    path:     /sub-item/{product}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productSubProduct }

webservice_product_sub_item_cart:
    path:     /sub-item/{product}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productSubProductCart }

webservice_module_page:
    path:     /{module}/{slug}
    defaults: { _controller: FrontendBundle:WebServiceModule:modulePage }

webservice_module_category:
    path:     /category/{module}/{slug}
    defaults: { _controller: FrontendBundle:WebServiceModule:moduleCategory }


webservice_product_promotion:
    path:     /{slug}/product-promotion
    defaults: { _controller: FrontendBundle:WebServiceProduct:promotion }

webservice_product_tag:
    path:     /{slug}/product-tag
    defaults: { _controller: FrontendBundle:WebServiceProduct:tag }

webservice_product_discount:
    path:     /{slug}/product-discount
    defaults: { _controller: FrontendBundle:WebServiceProduct:discount }

webservice_contact:
    path:     /contact
    defaults: { _controller: FrontendBundle:WebServiceModule:contact }

webservice_product_cart_details:
    path:     /cart-details
    defaults: { _controller: FrontendBundle:WebServiceProduct:productCart }

webservice_product:
    path:     /product
    defaults: { _controller: FrontendBundle:WebServiceProduct:product }



webservice_customer_register:
    path:     /register
    defaults: { _controller: FrontendBundle:WebServiceCustomer:register }

webservice_customer_create:
    path:     /register-customer-create
    defaults: { _controller: FrontendBundle:WebServiceCustomer:create }

webservice_customer_insert:
    path:     /register-customer-insert
    defaults: { _controller: FrontendBundle:WebServiceCustomer:insert }
    methods:  POST
    options:
            expose: true

webservice_customer_confirm:
    path:     /registration-confirm
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }

webservice_customer_checking:
    path:      /checking-username
    defaults: { _controller: FrontendBundle:WebServiceCustomer:userChecking }
    methods:  GET
    options:
            expose: true

webservice_customer_login:
    path:     /customer-login
    defaults: { _controller:  FrontendBundle:WebServiceCustomer:domainLogin }

webservice_login:
    path:     /customer-login
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }


webservice_module:
    path:     /{module}
    defaults: { _controller: FrontendBundle:WebServiceModule:module }


