ecommercesubdomain:
    path:     /
    defaults: { _controller: FrontendBundle:WebService:index }

webservice_product_details:
    path:     /product/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productDetails }

webservice_product_modal:
    path:     /product-modal/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productModal }

webservice_product_checkout:
    path:     /product-check-our
    defaults: { _controller: FrontendBundle:WebServiceProduct:checkout }

webservice_product_cart:
    path:     /cart/{product}/{subitem}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productAddCart }
    methods:  POST
    options:
            expose: true

webservice_product_wishlist:
    path:     /wishlist/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productAddWishList }

webservice_product_sub_item:
    path:     /sub-item/{product}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productSubProduct }

webservice_product_sub_item_cart:
    path:     /sub-item/{product}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productSubProductCart }

webservice_module_page:
    path:     /{module}/{slug}
    defaults: { _controller: FrontendBundle:WebServiceModule:modulePage }

webservice_module_category:
    path:     /category/{module}/{slug}
    defaults: { _controller: FrontendBundle:WebServiceModule:moduleCategory }


webservice_contact:
    path:     /contact
    defaults: { _controller: FrontendBundle:WebServiceModule:contact }

webservice_product_cart_details:
    path:     /cart-details
    defaults: { _controller: FrontendBundle:WebServiceProduct:productCart }

webservice_product:
    path:     /product
    defaults: { _controller: FrontendBundle:WebServiceProduct:product }

webservice_customer_register:
    path:     /register
    defaults: { _controller: FrontendBundle:WebServiceCustomer:register }

webservice_customer_create:
    path:     /customer-registration-create
    defaults: { _controller: FrontendBundle:WebServiceCustomer:create }

webservice_customer_insert:
    path:     /customer-registration-insert
    defaults: { _controller: FrontendBundle:WebServiceCustomer:insert }
    methods:  POST
    options:
            expose: true

webservice_customer_confirm:
    path:     /customer-registration-confirm
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }

webservice_customer_checking:
    path:      /username/checking
    defaults: { _controller: FrontendBundle:WebServiceCustomer:userChecking }
    methods:  POST
    options:
            expose: true

webservice_customer_login:
    path:     /customer-login
    defaults: { _controller:  FrontendBundle:WebServiceCustomer:domainLogin }

webservice_login:
    path:     /customer-login
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }

webservice_module:
    path:     /{module}
    defaults: { _controller: FrontendBundle:WebServiceModule:module }

