ecommercesubdomain:
    path:     /
    defaults: { _controller: FrontendBundle:WebService:index }

webservice_sms_receive:
    path:     /receive/sms
    defaults: { _controller: FrontendBundle:SmsEmailReceive:smsReceive}
    options:
            expose: true

webservice_email_receive:
    path:     /receive/email-sender
    defaults: { _controller: FrontendBundle:SmsEmailReceive:emailReceive}
    methods:  POST
    options:
            expose: true

webservice_news_letter_receive:
    path:     /receive/news-letter-sender
    defaults: { _controller: FrontendBundle:SmsEmailReceive:newsLetterReceive}
    methods:  POST
    options:
            expose: true

webservice_captch:
    path:     /captcha/recheck
    defaults: { _controller: FrontendBundle:SmsEmailReceive:captcha}
    methods:  POST
    options:
            expose: true

webservice_product_details:
    path:     /product/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productDetails }

webservice_product_modal:
    path:     /product-modal/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productModal }


webservice_product_cart:
    path:     /cart/{product}/{subitem}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productAddCart }
    methods:  POST
    options:
            expose: true

webservice_product_single_cart:
    path:     /single-cart/{product}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productAddSingleCart }
    methods:  GET
    options:
            expose: true

webservice_product_cart_update:
    path:     /cart/product-update/{cartid}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productUpdateCart }
    methods:  GET
    options:
            expose: true

webservice_product_cart_ajax_details:
    path:      /cart/product-details
    defaults: { _controller: FrontendBundle:WebServiceProduct:productCartDetails }

webservice_product_cart_remove:
    path:      /cart/product-remove/{cartid}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productRemoveCart }

webservice_product_wishlist:
    path:     /wishlist/{item}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productAddWishList }

webservice_product_sub_item:
    path:     /sub-item/{product}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productSubProduct }

webservice_product_sub_item_cart:
    path:     /sub-item/{product}
    defaults: { _controller: FrontendBundle:WebServiceProduct:productSubProductCart }

webservice_product_inline_item_load:
    path:     /inline-product-load/{product}
    defaults: { _controller: FrontendBundle:WebServiceProduct:inlineSubProduct }

webservice_module_page:
    path:     /{module}/{slug}
    defaults: { _controller: FrontendBundle:WebServiceModule:modulePage }

webservice_module_category:
    path:     /category/{module}/{slug}
    defaults: { _controller: FrontendBundle:WebServiceModule:moduleCategory }

webservice_product_category:
    path:     /product/category/{id}
    defaults: { _controller: FrontendBundle:WebServiceProduct:category }

webservice_product_promotion:
    path:     /product/promotion/{id}
    defaults: { _controller: FrontendBundle:WebServiceProduct:promotion }

webservice_product_tag:
    path:     /product/tag/{id}
    defaults: { _controller: FrontendBundle:WebServiceProduct:tag }

webservice_product_discount:
    path:     /product/discount/{id}
    defaults: { _controller: FrontendBundle:WebServiceProduct:discount }

webservice_product_brand:
    path:     /product/brand/{id}
    defaults: { _controller: FrontendBundle:WebServiceProduct:brand }

webservice_contact:
    path:     /contact
    defaults: { _controller: FrontendBundle:WebServiceModule:contact }

webservice_product_cart_details:
    path:     /basket
    defaults: { _controller: FrontendBundle:WebServiceProduct:productCart }

webservice_product:
    path:     /product
    defaults: { _controller: FrontendBundle:WebServiceProduct:product }

webservice_customer_register:
    path:     /register
    defaults: { _controller: FrontendBundle:WebServiceCustomer:register }

webservice_customer_create:
    path:     /register-customer-create
    defaults: { _controller: FrontendBundle:WebServiceCustomer:create }

webservice_customer_insert:
    path:     /register-customer-insert
    defaults: { _controller: FrontendBundle:WebServiceCustomer:insert }
    methods:  POST
    options:
            expose: true

webservice_customer_confirm:
    path:     /registration-confirm
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }

webservice_customer_checking:
    path:      /checking-username
    defaults: { _controller: FrontendBundle:WebServiceCustomer:userChecking }
    methods:  GET
    options:
            expose: true

webservice_customer_login:
    path:     /customer-login
    defaults: { _controller:  FrontendBundle:WebServiceCustomer:domainLogin }

webservice_login:
    path:     /customer-login
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }

webservice_search:
    path:     /content-search
    defaults: { _controller: FrontendBundle:WebServiceModule:search }

webservice_module:
    path:     /{module}
    defaults: { _controller: FrontendBundle:WebServiceModule:module }

frontend_category:
    path:     /category/{slug}
    defaults: { _controller: FrontendBundle:Default:category }

frontend_brand:
    path:     /brand/{slug}
    defaults: { _controller: FrontendBundle:Default:brand }

