
inventory_customer:
    resource: "@DomainUserBundle/Resources/config/routing/customerInventory.yml"
    prefix:   /inventory/customer

domain_notification:
    resource: "@DomainUserBundle/Resources/config/routing/notificationconfig.yml"
    prefix:   /domain/notification

domain_employee_branch:
    resource: "@DomainUserBundle/Resources/config/routing/employee_branch.yml"
    prefix:   /hr/branch-employee

domain_branch:
    resource: "@DomainUserBundle/Resources/config/routing/branches.yml"
    prefix:   /hr/branch

domain_store:
    resource: "@DomainUserBundle/Resources/config/routing/store.yml"
    prefix:   /hr/store

domain_user_customer:
    resource: "@DomainUserBundle/Resources/config/routing/customer.yml"
    prefix:   /crm

domain_user_domain:
    resource: "@DomainUserBundle/Resources/config/routing/domainuser.yml"
    prefix:   /hr/employee

domain_agent_user:
    resource: "@DomainUserBundle/Resources/config/routing/agent.yml"
    prefix:   /hr/agent

domain_agent_payment:
    resource: "@DomainUserBundle/Resources/config/routing/agentpayment.yml"
    prefix:   /hr/agent-payment
