inventory_customer:
    resource: "@DomainUserBundle/Resources/config/routing/customerInventory.yml"
    prefix:   /inventory/customer

domain_user_customer:
    resource: "@DomainUserBundle/Resources/config/routing/customer.yml"
    prefix:   /crm

domain_user_domain:
    resource: "@DomainUserBundle/Resources/config/routing/domainuser.yml"
    prefix:   /hr/employee
