services:
#    domain_user.example:
#        class: Appstore\Bundle\DomainUserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    appstore.customer.event.listener:
        class: Appstore\Bundle\DomainUserBundle\EventListener\CustomerListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
