business_invoice_distribution_store_payment:
    path:     /{invoice}/store-payment
    defaults: { _controller: "BusinessBundle:Distributor:storePayment" }
    methods:  POST
    options:
            expose: true

business_invoice_distribution_store_create:
    path:     /store-create
    defaults: { _controller: "BusinessBundle:Distributor:storeCreate" }
    methods:  POST
    options:
        expose: true

business_invoice_distributor_ledger_delete:
    path:     /{invoice}/{id}/delete-ledger
    defaults: { _controller: "BusinessBundle:Distributor:deleteLedger" }


business_invoice_distributor_item_update:
    path:     /sales-item-update
    defaults: { _controller: "BusinessBundle:Invoice:invoiceItemUpdate" }
    methods:  POST
    options:
            expose: true

