business_invoice:
    path:     /
    defaults: { _controller: "BusinessBundle:Invoice:index" }

business_invoice_show:
    path:     /{id}/show
    defaults: { _controller: "BusinessBundle:Invoice:show" }

business_invoice_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:Invoice:new" }

business_invoice_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:Invoice:edit" }

business_invoice_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "BusinessBundle:Invoice:particularSearch" }
    options:
           expose: true


business_item_unit_search:
    path:     /item-unit-search
    defaults: { _controller: "BusinessBundle:Invoice:autoUnitSearch" }
    options:
            expose: true


business_invoice_particular_add:
    path:     /{invoice}/particular-add
    defaults: { _controller: "BusinessBundle:Invoice:addParticular" }
    methods:  POST
    options:
            expose: true

business_invoice_discount_update:
    path:     /dicount-update
    defaults: { _controller: "BusinessBundle:Invoice:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true


business_invoice_payment:
    path:     /{invoice}/invoice-payment
    defaults: { _controller: "BusinessBundle:Invoice:addPayment" }
    methods:  POST
    options:
            expose: true

business_invoice_medicine_add:
    path:     /{invoice}/medicine-add
    defaults: { _controller: "BusinessBundle:Invoice:addMedicine" }
    methods:  POST
    options:
            expose: true

business_invoice_medicine_delete:
    path:     /{id}/medicine-delete
    defaults: { _controller: "BusinessBundle:Invoice:deleteMedicine" }


business_invoice_appointment_datetime_check:
    path:     /treatment-appointment-datetime-check
    defaults: { _controller: "BusinessBundle:Invoice:treatmentAppointmentDatetime" }
    methods:  POST
    options:
            expose: true

business_invoice_accessories_add:
    path:     /{invoice}/accessories-add
    defaults: { _controller: "BusinessBundle:Invoice:addAccessories" }
    methods:  POST
    options:
            expose: true

business_invoice_accessories_delete:
    path:     /{id}/accessories-delete
    defaults: { _controller: "BusinessBundle:Invoice:deleteAccessories" }

business_invoice_accessories_approved:
    path:     /{id}/accessories-approved
    defaults: { _controller: "BusinessBundle:Invoice:approvedAccessories" }


business_invoice_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "BusinessBundle:Invoice:approve" }
    methods:  POST
    options:
            expose: true

business_invoice_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:Invoice:update" }
    methods:  [POST, PUT]

business_invoice_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:Invoice:delete" }

business_invoice_reverse_show:
    path:     /{id}/invoice-reverse-show
    defaults: { _controller: "BusinessBundle:Invoice:InvoiceReverseShow" }


business_invoice_particular_delete:
    path:     /{invoice}/{id}/particular-delete
    defaults: { _controller: "BusinessBundle:Invoice:invoiceParticularDelete" }

business_invoice_print_invoice:
    path:     /{id}/print
    defaults: { _controller: "BusinessBundle:Invoice:invoicePrint" }

business_prescription_preview:
    path:     /{invoice}/print-preview
    defaults: { _controller: "BusinessBundle:Invoice:invoicePrintPreview" }

business_invoice_process_update:
    path:     /hms-invoice/upadte-process
    defaults: { _controller: "BusinessBundle:Invoice:invoiceProcessUpdate" }
    methods:  POST
    options:
            expose: true

business_invoice_status_select:
    path:     /invoice-status-select
    defaults: { _controller: "BusinessBundle:Invoice:statusSelect" }
    options:
           expose: true

business_invoice_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "BusinessBundle:Invoice:deleteEmptyInvoice" }

business_invoice_customer_details:
    path:     /invoice-patient-details
    defaults: { _controller: "DomainUserBundle:CustomerHms:details" }
    methods:  POST
    options:
           expose: true

business_invoice_add_patient:
    path:     /{id}/invoice-patient-add
    defaults: { _controller: "BusinessBundle:Invoice:addPatient" }
    methods:  [POST, PUT]
    options:
            expose: true

business_treatment_inline_update:
    path:     /inline-update
    defaults: { _controller: "BusinessBundle:Invoice:inlineUpdate" }


business_invoice_procedure_search:
    path:     /procedure-search
    defaults: { _controller: "BusinessBundle:Invoice:procedureSearch" }
    options:
            expose: true

business_invoice_auto_particular_search:
    path:     /auto-particular-search
    defaults: { _controller: "BusinessBundle:Invoice:autoParticularSearch" }
    options:
            expose: true

business_invoice_investigation_search:
    path:     /auto-investigation-search
    defaults: { _controller: "BusinessBundle:Invoice:autoInvestigationSearch" }
    options:
            expose: true

business_invoice_investigation_procedure:
    path:     /{invoice}/investigation-file-procedure
    defaults: { _controller: "BusinessBundle:Invoice:investigationProcedure" }
    methods:  POST
    options:
           expose: true

business_treatment_plan:
    path:     /treatment-plan
    defaults: { _controller: "BusinessBundle:TreatmentPlan:index" }

business_treatment_appointment_schedule:
    path:     /treatment-appointment-date
    defaults: { _controller: "BusinessBundle:TreatmentPlan:appointmentDateSchedule" }
    methods:  POST
    options:
           expose: true

business_invoice_appointment_schedule_time:
    path:     /treatment-appointment-free-time
    defaults: { _controller: "BusinessBundle:TreatmentPlan:appointmentFreeTimeSchedule" }
    options:
           expose: true

business_treatment_date_wise_schedule:
    path:     /treatment-appointment-date-wise-schedule
    defaults: { _controller: "BusinessBundle:TreatmentPlan:dateWiseSchedule" }
    methods:  POST
    options:
           expose: true

business_treatment_plan_sms:
    path:     /{patient}/{id}/send-sms
    defaults: { _controller: "BusinessBundle:TreatmentPlan:sendSmsPlan" }

