business_product:
    path:     /
    defaults: { _controller: "DmsBundle:Medicine:index" }

business_product_create:
    path:     /create
    defaults: { _controller: "DmsBundle:Medicine:create" }
    methods:  POST

business_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "DmsBundle:Medicine:edit" }

business_product_update:
    path:     /{id}/update
    defaults: { _controller: "DmsBundle:Medicine:update" }
    methods:  [POST, PUT]

business_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "DmsBundle:Medicine:delete" }

business_product_status:
    path:     /{id}/status
    defaults: { _controller: "DmsBundle:Medicine:status" }

business_product_inline:
    path:     /inline-update
    defaults: { _controller: "DmsBundle:Medicine:inlineUpdate" }