business_report_purchase_summary:
    path:     /purchase-overview
    defaults: { _controller: "BusinessBundle:Report:purchaseOverview" }

business_report_purchase_ledger:
    path:     /purchase-vendor-outstanding
    defaults: { _controller: "BusinessBundle:Report:purchaseVendor" }

business_report_purchase_vendor_details:
    path:     /purchase-vendor-details
    defaults: { _controller: "BusinessBundle:Report:purchaseVendorDetails" }

business_report_commission_stock:
    path:     /commission-stock-item
    defaults: { _controller: "BusinessBundle:Report:salesCommissionStockItem" }

business_report_purchase_stock_price:
    path:     /purchase-stock-price
    defaults: { _controller: "BusinessBundle:Report:purchaseVendorSales" }

business_report_item_stock_price:
    path:     /purchase-stock-price
    defaults: { _controller: "BusinessBundle:Report:purchaseVendorSales" }

business_report_item_stock:
    path:     /purchase-stock-price
    defaults: { _controller: "BusinessBundle:Report:purchaseVendorSales" }


business_report_sales_vendor_customer:
    path:     /vendor-base-sales
    defaults: { _controller: "BusinessBundle:Report:salesVendorCustomer" }

business_report_purchase_brand_sales:
    path:     /purchase-brand-sales
    defaults: { _controller: "BusinessBundle:Report:purchaseBrandSales" }


business_report_purchase_brand_sales_details:
    path:     /purchase-brand-sales-details
    defaults: { _controller: "BusinessBundle:Report:purchaseBrandSalesDetails" }


business_report_product_stock_sales:
    path:     /product-vendor-stock-sales
    defaults: { _controller: "BusinessBundle:Report:productPurchaseStockSales" }

business_report_product_stock_sales_price:
    path:     /product-brand-stock-sales-price
    defaults: { _controller: "BusinessBundle:Report:productPurchaseStockSalesPrice" }


business_report_purchase_details:
    path:     /purchase-vendor
    defaults: { _controller: "BusinessBundle:Report:purchaseVendor" }

business_report_purchase_stock:
    path:     /purchase-vendor-
    defaults: { _controller: "BusinessBundle:Report:purchaseVendor" }

business_report_sales_summary:
    path:     /sales-overview
    defaults: { _controller: "BusinessBundle:Report:salesOverview" }

business_report_sales_details:
    path:     /sales-details
    defaults: { _controller: "BusinessBundle:Report:salesDetails" }

business_report_sales_stock:
    path:     /sales-stock
    defaults: { _controller: "BusinessBundle:Report:salesStockItem" }

business_report_customer_sales_item:
    path:     /customer-sales-item
    defaults: { _controller: "BusinessBundle:Report:customerSalesItem" }

business_report_sales_user:
    path:     /sales-user
    defaults: { _controller: "BusinessBundle:Report:salesUser" }

business_report_sales_sr:
    path:     /sales-sr
    defaults: { _controller: "BusinessBundle:Report:salesSr" }

business_report_sales_dsr:
    path:     /sales-dsr
    defaults: { _controller: "BusinessBundle:Report:salesDsr" }

business_report_sales_area:
    path:     /sales-area
    defaults: { _controller: "BusinessBundle:Report:salesArea" }

business_report_sales_user_monthly:
    path:     /sales-user-monthly
    defaults: { _controller: "BusinessBundle:Report:monthlyUserSales" }

business_report_vendor_commission_sales:
    path:     /vendor-commission-sales
    defaults: { _controller: "BusinessBundle:Report:vendorCommissionBaseSales" }

business_report_customer_commission_sales:
    path:     /customer-commission-sales
    defaults: { _controller: "BusinessBundle:Report:customerCommissionBaseSales" }

