business_stock:
    path:     /
    defaults: { _controller: "BusinessBundle:Stock:index" }

business_stock_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:Stock:new" }

business_stock_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:Stock:create" }
    methods:  POST

business_stock_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:Stock:edit" }

business_stock_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:Stock:update" }
    methods:  [POST, PUT]

business_stock_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:Stock:delete" }

business_stock_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:Stock:status" }

business_stock_inline:
    path:     /inline-update
    defaults: { _controller: "BusinessBundle:Stock:inlineUpdate" }

business_stock_production:
    path:     /{id}/production
    defaults: { _controller: "BusinessBundle:Stock:production" }