<?php

namespace Appstore\Bundle\EcommerceBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * OnlineOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BkashAccountRepository extends EntityRepository
{
}
