<?php

namespace Appstore\Bundle\EcommerceBundle\Repository;
use Appstore\Bundle\EcommerceBundle\Entity\EcommerceConfig;
use Doctrine\ORM\EntityRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryLocationRepository extends EntityRepository
{

    public function getApiDeliveryLocation($config)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->select('e.id as id','e.name as name');
        $qb->where("e.ecommerceConfig = :option")->setParameter('option', $config->getId());
        $result = $qb->getQuery()->getArrayResult();
        return $result;

    }
}
