medicine_medicine:
    resource: "@MedicineBundle/Resources/config/routing/medicinebrand.yml"
    prefix:   /drug

medicine_medicine_user:
    resource: "@MedicineBundle/Resources/config/routing/medicine.yml"
    prefix:   /drug-user

medicine_medicine_company:
    resource: "@MedicineBundle/Resources/config/routing/medicinecompany.yml"
    prefix:   /drug-company

medicine_dental_investigation:
    resource: "@MedicineBundle/Resources/config/routing/dentalinvestigation.yml"
    prefix:   /dental-investigation

medicine_medicine_config:
    resource: "@MedicineBundle/Resources/config/routing/config.yml"
    prefix:   /config

medicine_medicine_stock:
    resource: "@MedicineBundle/Resources/config/routing/stock.yml"
    prefix:   /stock

medicine_medicine_sales:
    resource: "@MedicineBundle/Resources/config/routing/sales.yml"
    prefix:   /sales

medicine_medicine_purchase:
    resource: "@MedicineBundle/Resources/config/routing/purchase.yml"
    prefix:   /purchase

medicine_medicine_instantpurchase:
    resource: "@MedicineBundle/Resources/config/routing/instantpurchase.yml"
    prefix:   /instant-purchase

medicine_medicine_vendor:
    resource: "@MedicineBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor

medicine_medicine_particular:
    resource: "@MedicineBundle/Resources/config/routing/particular.yml"
    prefix:   /particular

medicine_homepage:
    path:     /
    defaults: { _controller: MedicineBundle:Default:index }
