medicine_medicine:
    resource: "@MedicineBundle/Resources/config/routing/medicinecompany.yml"
    prefix:   /medicine

medicine_homepage:
    path:     /hello/{name}
    defaults: { _controller: MedicineBundle:Default:index }
