services:
#    medicine.example:
#        class: Appstore\Bundle\MedicineBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    appstore.medicine.stock.event.listener:
        class: Appstore\Bundle\MedicineBundle\EventListener\MedicineStockListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.medicine.purchase.event.listener:
        class: Appstore\Bundle\MedicineBundle\EventListener\MedicinePurchaseListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.medicine.purchase.item.event.listener:
        class: Appstore\Bundle\MedicineBundle\EventListener\MedicinePurchaseItemListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.medicine.sales.event.listener:
            class: Appstore\Bundle\MedicineBundle\EventListener\MedicineSalesListener
            tags:
                - { name: doctrine.event_listener, event: prePersist }



