<?php

namespace Appstore\Bundle\DomainUserBundle\Repository;
use Appstore\Bundle\DomainUserBundle\Entity\CustomerInbox;
use Doctrine\ORM\EntityRepository;

/**
 * BranchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchesRepository extends EntityRepository
{


}
