branch:
    path:     /
    defaults: { _controller: "SettingContentBundle:Branch:index" }

branch_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:Branch:show" }

branch_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:Branch:new" }

branch_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:Branch:create" }
    requirements: { _method: post }

branch_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:Branch:edit" }

branch_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:Branch:update" }
    requirements: { _method: post|put }

branch_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:Branch:delete" }


branch_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:Branch:status" }

branch_print_list:
    path:     /print-list
    defaults: { _controller: "SettingContentBundle::printList" }

branch_pdf_list:
    path:     /pdf-list
    defaults: { _controller: "SettingContentBundle:Branch:pdfList" }

branch_export_list:
    path:     /export-list
    defaults: { _controller: "SettingContentBundle:Branch:exportList" }

branch_print:
    path:     /{id}/print-details
    defaults: { _controller: "SettingContentBundle:Branch:printDetails" }

branch_pdf:
    path:     /{id}/pdf-details
    defaults: { _controller: "SettingContentBundle:Branch:pdfDetails" }

branch_import:
    path:     /import
    defaults: { _controller: "SettingContentBundle:Branch:import" }

branch_export:
    path:     /{id}/export-details
    defaults: { _controller: "SettingContentBundle:Branch:exportDetails" }

