homepage:
    path:     /
    defaults: { _controller: "SettingContentBundle:HomePage:index" }

homepage_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:HomePage:show" }

homepage_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:HomePage:new" }

homepage_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:HomePage:create" }
    requirements: { _method: post }

homepage_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:HomePage:edit" }

homepage_modify:
    path:     /modify
    defaults: { _controller: "SettingContentBundle:HomePage:modify" }

homepage_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:HomePage:update" }
    requirements: { _method: post|put }

homepage_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:HomePage:delete" }

