newses:
    path:     /listing
    defaults: { _controller: "SettingContentBundle:News:listing" }

newses_delete:
    path:     listing/delete
    defaults: { _controller: "SettingContentBundle:News:listingDelete" }

news:
    path:     /
    defaults: { _controller: "SettingContentBundle:News:index" }

news_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:News:show" }

news_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:News:new" }

news_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:News:create" }
    requirements: { _method: post }

news_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:News:edit" }

news_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:News:update" }
    requirements: { _method: post|put }

news_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:News:delete" }
    requirements: { _method: post|delete }

news_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:News:status" }

news_print_list:
    path:     /print-list
    defaults: { _controller: "SettingContentBundle:News:printList" }

news_pdf_list:
    path:     /pdf-list
    defaults: { _controller: "SettingContentBundle:News:pdfList" }

news_export_list:
    path:     /export-list
    defaults: { _controller: "SettingContentBundle:News:exportList" }

news_print:
    path:     /{id}/print-details
    defaults: { _controller: "SettingContentBundle:News:printDetails" }

news_pdf:
    path:     /{id}/pdf-details
    defaults: { _controller: "SettingContentBundle:News:pdfDetails" }

news_import:
    path:     /import
    defaults: { _controller: "SettingContentBundle:News:import" }

news_export:
    path:     /{id}/export-details
    defaults: { _controller: "SettingContentBundle:News:exportDetails" }

