noticeboard:
    path:     /
    defaults: { _controller: "SettingContentBundle:NoticeBoard:index" }

noticeboard_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:NoticeBoard:show" }

noticeboard_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:NoticeBoard:new" }

noticeboard_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:NoticeBoard:create" }
    requirements: { _method: post }

noticeboard_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:NoticeBoard:edit" }

noticeboard_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:NoticeBoard:status" }

noticeboard_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:NoticeBoard:update" }
    requirements: { _method: post|put }

noticeboard_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:NoticeBoard:delete" }
    requirements: { _method: post|delete }

noticeboard_print_list:
    path:     /print-list
    defaults: { _controller: "SettingContentBundle:NoticeBoard:printList" }

noticeboard_pdf_list:
    path:     /pdf-list
    defaults: { _controller: "SettingContentBundle:NoticeBoard:pdfList" }

noticeboard_export_list:
    path:     /export-list
    defaults: { _controller: "SettingContentBundle:NoticeBoard:exportList" }

noticeboard_print:
    path:     /{id}/print-details
    defaults: { _controller: "SettingContentBundle:NoticeBoard:printDetails" }

noticeboard_pdf:
    path:     /{id}/pdf-details
    defaults: { _controller: "SettingContentBundle:NoticeBoard:pdfDetails" }

noticeboard_import:
    path:     /import
    defaults: { _controller: "SettingContentBundle:NoticeBoard:import" }

noticeboard_export:
    path:     /{id}/export-details
    defaults: { _controller: "SettingContentBundle:NoticeBoard:exportDetails" }

