tradeitem:
    path:     /
    defaults: { _controller: "SettingContentBundle:TradeItem:index" }

tradeitem_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:TradeItem:show" }

tradeitem_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:TradeItem:new" }

tradeitem_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:TradeItem:create" }
    methods:  POST

tradeitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:TradeItem:edit" }


tradeitem_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:TradeItem:status" }

tradeitem_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:TradeItem:update" }
    methods:  [POST, PUT]

tradeitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:TradeItem:delete" }

