restaurant_report:
    resource: "@RestaurantBundle/Resources/config/routing/report.yml"
    prefix:   /report

restaurant_purchase:
    resource: "@RestaurantBundle/Resources/config/routing/purchase.yml"
    prefix:   /purchase

restaurant_production:
    resource: "@RestaurantBundle/Resources/config/routing/production.yml"
    prefix:   /production

restaurant_vendor:
    resource: "@RestaurantBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor

restaurant_invoice:
    resource: "@RestaurantBundle/Resources/config/routing/invoice.yml"
    prefix:   /invoice


restaurant_particular:
    resource: "@RestaurantBundle/Resources/config/routing/particular.yml"
    prefix:   /particular

restaurant_category:
    resource: "@RestaurantBundle/Resources/config/routing/category.yml"
    prefix:   /category

restaurant_product:
    resource: "@RestaurantBundle/Resources/config/routing/product.yml"
    prefix:   /product

restaurant_stock:
    resource: "@RestaurantBundle/Resources/config/routing/stock.yml"
    prefix:   /stock

restaurant_config:
    resource: "@RestaurantBundle/Resources/config/routing/config.yml"
    prefix:   /config

restaurant_homepage:
    path:     /dashoard
    defaults: { _controller: RestaurantBundle:Default:index }
