account_expense_purchase:
    path:     /
    defaults: { _controller: "AccountingBundle:Purchase:index" }

account_expense_purchase_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:Purchase:new" }

account_expense_purchase_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:Purchase:edit" }

account_expense_purchase_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:Purchase:update" }
    methods:  [POST, PUT]


account_expense_purchase_status:
    path:     /{id}/status
    defaults: { _controller: "AccountingBundle:Purchase:status" }

account_expense_purchase_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:Purchase:delete" }
