hms_hms_report_balance:
    path:     /balance-sheet
    defaults: { _controller: "AccountingBundle:Report:balance" }

hms_report_balance_pdf:
    path:     /balance-sheet
    defaults: { _controller: "AccountingBundle:Report:balance" }

hms_report_income:
    path:     /income
    defaults: { _controller: "AccountingBundle:HmsReport:income" }

hms_report_income_pdf:
    path:     /income-pdf
    defaults: { _controller: "AccountingBundle:HmsReport:pdfIncome" }

hms_report_income_print:
    path:     /income-print
    defaults: { _controller: "AccountingBundle:HmsReport:printIncome" }

hms_report_monthly_income:
    path:     /monthly-income
    defaults: { _controller: "AccountingBundle:HmsReport:monthlyIncome" }

account_bank_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountBank:show" }

