business_report:
    resource: "@BusinessBundle/Resources/config/routing/report.yml"
    prefix:   /report

business_purchase:
    resource: "@BusinessBundle/Resources/config/routing/purchase.yml"
    prefix:   /purchase

business_vendor_stock:
    resource: "@BusinessBundle/Resources/config/routing/vendorstock.yml"
    prefix:   /vendor-stock

business_vendor:
    resource: "@BusinessBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor

business_invoice:
    resource: "@BusinessBundle/Resources/config/routing/invoice.yml"
    prefix:   /invoice

business_stock:
    resource: "@BusinessBundle/Resources/config/routing/stock.yml"
    prefix:   /stock

business_product:
    resource: "@BusinessBundle/Resources/config/routing/product.yml"
    prefix:   /product

business_product_production:
    resource: "@BusinessBundle/Resources/config/routing/production.yml"
    prefix:   /product-production

business_stock_transfer:
    resource: "@BusinessBundle/Resources/config/routing/stock_transfer.yml"
    prefix:   /stock-transfer

business_damage:
    resource: "@BusinessBundle/Resources/config/routing/damage.yml"
    prefix:   /damage

business_category:
    resource: "@BusinessBundle/Resources/config/routing/category.yml"
    prefix:   /category

business_wearhouse:
    resource: "@BusinessBundle/Resources/config/routing/wearhouse.yml"
    prefix:   /wear-house

business_reverse:
    resource: "@BusinessBundle/Resources/config/routing/reverse.yml"
    prefix:   /reverse

business_config:
    resource: "@BusinessBundle/Resources/config/routing/config.yml"
    prefix:   /config

business_homepage:
    path:     /dashboard
    defaults: { _controller: BusinessBundle:Default:index }
