services:
#    appstore_dms.example:
#        class: Appstore\Bundle\DmsBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    

    appstore.business.particular.event.listener:
        class: Appstore\Bundle\BusinessBundle\EventListener\BusinessParticularListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.business.invoice.event.listener:
        class: Appstore\Bundle\BusinessBundle\EventListener\BusinessInvoiceListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    appstore.business.purchase.event.listener:
        class: Appstore\Bundle\BusinessBundle\EventListener\BusinessPurchaseListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

