appearancesidebarwidget:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:Template:index" }

appearancesidebarwidget_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:Template:show" }

appearancesidebarwidget_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:Template:new" }

appearancesidebarwidget_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:Template:create" }
    methods:  POST

appearancesidebarwidget_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:Template:edit" }

appearancesidebarwidget_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:Template:update" }
    methods:  [POST, PUT]

appearancesidebarwidget_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:Template:delete" }

appearancesidebarwidget_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:Template:status" }

appearancesidebarwidget_resizing:
    path:     /resizing
    defaults: { _controller: "SettingAppearanceBundle:Template:resize" }

appearancesidebarwidget_sorted:
    path:     /sorted
    defaults: { _controller: "SettingAppearanceBundle:Template:sorted" }
