domain_hr_attendance:
    path:     /
    defaults: { _controller: "DomainUserBundle:HrAttendance:index" }

domain_hr_attendance_show:
    path:     /{month}/show
    defaults: { _controller: "DomainUserBundle:HrAttendance:show" }

domain_hr_attendance_month:
    path:     /current-month
    defaults: { _controller: "DomainUserBundle:HrAttendance:month" }

domain_hr_attendance_add:
    path:     /{user}/add
    defaults: { _controller: "DomainUserBundle:HrAttendance:addAttendance" }
    methods:  POST
    options:
           expose: true

domain_hr_attendance_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:HrAttendance:delete" }
