domain_customer_homepage:
    path:     /dashboard
    defaults: { _controller: CustomerBundle:Customer:index }

customer_order_cart:
    path:     /order-cart
    defaults: { _controller: CustomerBundle:Customer:cart }

domain_customer_order:
    path:     /order
    defaults: { _controller: CustomerBundle:Customer:order }

domain_customer_payment:
    path:     /payment/{id}
    defaults: { _controller: CustomerBundle:Customer:payment }

domain_customer_order_process:
    path:      /{id}/{process}/order-process
    defaults: { _controller: CustomerBundle:Customer:process }
    methods:  [GET, PUT]

domain_order_ajax_payment:
    path:      /{id}/order-payment
    defaults: { _controller: "CustomerBundle:Customer:pay" }
    methods:  [POST]

domain_order_invoice:
    path:      /{id}/preorder-invoice
    defaults: { _controller: "EcommerceBundle:PreOrder:invoice" }