domain_customer_homepage:
    path:     /customer/dashboard
    defaults: { _controller: CustomerBundle:Customer:index }

domain_customer_order:
    path:     /customer/order
    defaults: { _controller: CustomerBundle:Customer:order }

domain_customer_payment:
    path:     /customer/payment/{id}
    defaults: { _controller: CustomerBundle:Customer:payment }

domain_customer_order_process:
    path:      /customer/{id}/{process}/order-process
    defaults: { _controller: CustomerBundle:Customer:process }
    methods:  [GET, PUT]

domain_order_ajax_payment:
    path:      /customer/{id}/order-payment
    defaults: { _controller: "CustomerBundle:Customer:pay" }
    methods:  [POST]

domain_order_invoice:
    path:      /customer/{id}/preorder-invoice
    defaults: { _controller: "EcommerceBundle:PreOrder:invoice" }