customer_domain_product:
    resource: "@CustomerBundle/Resources/config/routing/product.yml"
    prefix:   /product

customer_domain:
    resource: "@CustomerBundle/Resources/config/routing/domain.yml"
    prefix:   /domain

customer_order_process:
    resource: "@CustomerBundle/Resources/config/routing/order.yml"
    prefix:   /order

customer_pre_order_process:
    resource: "@CustomerBundle/Resources/config/routing/preorder.yml"
    prefix:   /pre-order

domain_customer_homepage:
    path:     /dashboard
    defaults: { _controller: "CustomerBundle:Customer:index" }




