customer_domain_product:
    resource: "@CustomerBundle/Resources/config/routing/product.yml"
    prefix:   /{shop}/product

customer_self:
    resource: "@CustomerBundle/Resources/config/routing/customer.yml"
    prefix:   /

customer_domain:
    resource: "@CustomerBundle/Resources/config/routing/domain.yml"
    prefix:   /

customer_order_process:
    resource: "@CustomerBundle/Resources/config/routing/order.yml"
    prefix:   /{shop}/order

customer_order_wishlist:
    resource: "@CustomerBundle/Resources/config/routing/wishlist.yml"
    prefix:   /{shop}/wishlist

customer_order_inbox:
    resource: "@CustomerBundle/Resources/config/routing/inbox.yml"
    prefix:   /{shop}/inbox

customer_pre_order_process:
    resource: "@CustomerBundle/Resources/config/routing/preorder.yml"
    prefix:   /{shop}/pre-order

agent_client:
    resource: "@CustomerBundle/Resources/config/routing/agentclient.yml"
    prefix:   /agent

customer_website:
    resource: "@CustomerBundle/Resources/config/routing/customerweb.yml"
    prefix:   /{shop}/content

domain_customer_homepage:
    path:     /{shop}/dashboard/
    defaults: { _controller: "CustomerBundle:Customer:index" }

domain_customer_domainpage:
    path:     /domaindas-hboard/
    defaults: { _controller: "CustomerBundle:Customer:customerDomain" }

customerweb_profile:
    path:     /{shop}/profile
    defaults: { _controller: "CustomerBundle:Profile:edit" }



