ecommerce_bkash:
    path:     /
    defaults: { _controller: "EcommerceBundle:BkashAccount:index" }

ecommerce_bkash_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:BkashAccount:show" }

ecommerce_bkash_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:BkashAccount:new" }

ecommerce_bkash_create:
    path:     /create
    defaults: { _controller: "EcommerceBundle:BkashAccount:create" }
    methods:  POST

ecommerce_bkash_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:BkashAccount:edit" }

ecommerce_bkash_update:
    path:     /{id}/update
    defaults: { _controller: "EcommerceBundle:BkashAccount:update" }
    methods:  [POST, PUT]

ecommerce_bkash_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:BkashAccount:delete" }

ecommerce_bkash_status:
    path:     /{id}/status
    defaults: { _controller: "EcommerceBundle:BkashAccount:status" }

