ecommerce_product:
    path:     /
    defaults: { _controller: "EcommerceBundle:EcommerceConfig:index" }

ecommerce_home:
    path:     /home
    defaults: { _controller: "EcommerceBundle:EcommerceConfig:update" }

ecommerce_promotion:
    path:     /promotion
    defaults: { _controller: "EcommerceBundle:EcommerceConfig:modify" }