ecommerceslider:
    path:     /
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:index" }

ecommerceslider_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:show" }

ecommerceslider_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:new" }

ecommerceslider_create:
    path:     /create
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:create" }
    methods:  POST

ecommerceslider_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:edit" }

ecommerceslider_modify:
    path:     /modify
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:modify" }

ecommerceslider_update:
    path:     /{id}/update
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:update" }
    methods:  [POST, PUT]

ecommerceslider_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:delete" }

ecommerceslider_status:
    path:     /{id}/status
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:status" }

ecommerceslider_sorting:
    path:     /sorting
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:sorting" }

ecommerceslider_sorted:
    path:     /sorted
    defaults: { _controller: "EcommerceBundle:EcommerceSlider:sorted" }
