openticket:
    path:     /
    defaults: { _controller: "TicketBundle:OpenTicket:index" }

openticket_show:
    path:     /{id}/show
    defaults: { _controller: "TicketBundle:OpenTicket:show" }

openticket_new:
    path:     /{ticket}/new
    defaults: { _controller: "TicketBundle:OpenTicket:new" }

openticket_create:
    path:     /create
    defaults: { _controller: "TicketBundle:OpenTicket:create" }
    methods:  POST

openticket_edit:
    path:     /{id}/edit
    defaults: { _controller: "TicketBundle:OpenTicket:edit" }

openticket_update:
    path:     /{id}/update
    defaults: { _controller: "TicketBundle:OpenTicket:update" }
    methods:  [POST, PUT]

openticket_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "TicketBundle:OpenTicket:approve" }
    options:
           expose: true

openticket_inline:
    path:     /inline-update
    defaults: { _controller: "TicketBundle:OpenTicket:inlineUpdate" }


openticket_delete:
    path:     /{id}/delete
    defaults: { _controller: "TicketBundle:OpenTicket:delete" }
    options:
           expose: true
